var d=!0,n=null,p=!1,r=window,s=void 0;function aa(a,b,c){if(c===s&&1===a.nodeType)if(c="data-"+b.replace(ba,"-$1").toLowerCase(),c=a.getAttribute(c),"string"==typeof c){try{c="true"===c?d:"false"===c?p:"null"===c?n:+c+""===c?+c:ca.test(c)?u.cc(c):c}catch(e){}u.data(a,b,c)}else c=s;return c}function ea(a){for(var b in a)if(!("data"===b&&u.Da(a[b]))&&"toJSON"!==b)return p;return d}function fa(){return p}function ga(){return d}function ha(a){return!a||!a.parentNode||11===a.parentNode.nodeType}
function ia(a,b){do a=a[b];while(a&&1!==a.nodeType);return a}function ka(a,b,c){b=b||0;if(u.d(b))return u.T(a,function(a,e){return!!b.call(a,e,a)===c});if(b.nodeType)return u.T(a,function(a){return a===b===c});if("string"==typeof b){var e=u.T(a,function(a){return 1===a.nodeType});if(la.test(b))return u.filter(b,e,!c);b=u.filter(b,e)}return u.T(a,function(a){return 0<=u.L(a,b)===c})}
function ma(a){var b=na.split("|");a=a.createDocumentFragment();if(a.createElement)for(;b.length;)a.createElement(b.pop());return a}function oa(a,b){if(1===b.nodeType&&u.Ob(a)){var c,e,f;e=u.e(a);var h=u.e(b,e),g=e.J;if(g)for(c in delete h.handle,h.J={},g){e=0;for(f=g[c].length;e<f;e++)u.event.add(b,c,g[c][e])}h.data&&(h.data=u.extend({},h.data))}}
function pa(a,b){var c;1===b.nodeType&&(b.Mc&&b.Mc(),b.mergeAttributes&&b.mergeAttributes(a),c=b.nodeName.toLowerCase(),"object"===c?(b.parentNode&&(b.outerHTML=a.outerHTML),u.c.mb&&a.innerHTML&&!u.trim(b.innerHTML)&&(b.innerHTML=a.innerHTML)):"input"===c&&qa.test(a.type)?(b.defaultChecked=b.checked=a.checked,b.value!==a.value&&(b.value=a.value)):"option"===c?b.selected=a.defaultSelected:"input"===c||"textarea"===c?b.defaultValue=a.defaultValue:"script"===c&&b.text!==a.text&&(b.text=a.text),b.removeAttribute(u.expando))}
function ra(a){return"undefined"!=typeof a.getElementsByTagName?a.getElementsByTagName("*"):"undefined"!=typeof a.querySelectorAll?a.querySelectorAll("*"):[]}function sa(a){qa.test(a.type)&&(a.defaultChecked=a.checked)}function ta(a,b){if(b in a)return b;for(var c=b.charAt(0).toUpperCase()+b.slice(1),e=b,f=ua.length;f--;)if(b=ua[f]+c,b in a)return b;return e}function va(a,b){return a=b||a,"none"===u.g(a,"display")||!u.contains(a.ownerDocument,a)}
function wa(a,b){for(var c,e,f=[],h=0,g=a.length;h<g;h++)c=a[h],c.style&&(f[h]=u.e(c,"olddisplay"),b?(!f[h]&&"none"===c.style.display&&(c.style.display=""),""===c.style.display&&va(c)&&(f[h]=u.e(c,"olddisplay",xa(c.nodeName)))):(e=w(c,"display"),!f[h]&&"none"!==e&&u.e(c,"olddisplay",e)));for(h=0;h<g;h++)if(c=a[h],c.style&&(!b||"none"===c.style.display||""===c.style.display))c.style.display=b?f[h]||"":"none";return a}function ya(a,b,c){return(a=za.exec(b))?Math.max(0,a[1]-(c||0))+(a[2]||"px"):b}
function Aa(a,b,c,e){b=c===(e?"border":"content")?4:"width"===b?1:0;for(var f=0;4>b;b+=2)"margin"===c&&(f+=u.g(a,c+Ba[b],d)),e?("content"===c&&(f-=parseFloat(w(a,"padding"+Ba[b]))||0),"margin"!==c&&(f-=parseFloat(w(a,"border"+Ba[b]+"Width"))||0)):(f+=parseFloat(w(a,"padding"+Ba[b]))||0,"padding"!==c&&(f+=parseFloat(w(a,"border"+Ba[b]+"Width"))||0));return f}
function Ca(a,b,c){var e="width"===b?a.offsetWidth:a.offsetHeight,f=d,h=u.c.boxSizing&&"border-box"===u.g(a,"boxSizing");if(0>=e||e==n){e=w(a,b);if(0>e||e==n)e=a.style[b];if(Da.test(e))return e;f=h&&(u.c.Eb||e===a.style[b]);e=parseFloat(e)||0}return e+Aa(a,b,c||(h?"border":"content"),f)+"px"}
function xa(a){if(Ea[a])return Ea[a];var b=u("<"+a+">").Dc(A.body),c=b.g("display");b.remove();if("none"===c||""===c){Fa=A.body.appendChild(Fa||u.extend(A.createElement("iframe"),{frameBorder:0,width:0,height:0}));if(!Ga||!Fa.createElement)Ga=(Fa.contentWindow||Fa.contentDocument).document,Ga.write("<!doctype html><html><body>"),Ga.close();b=Ga.body.appendChild(Ga.createElement(a));c=w(b,"display");A.body.removeChild(Fa)}return Ea[a]=c,c}
function Ha(a,b,c,e){var f;if(u.isArray(b))u.a(b,function(b,f){c||Ia.test(a)?e(a,f):Ha(a+"["+("object"==typeof f?b:"")+"]",f,c,e)});else if(!c&&"object"===u.type(b))for(f in b)Ha(a+"["+f+"]",b[f],c,e);else e(a,b)}function Ja(a){return function(b,c){"string"!=typeof b&&(c=b,b="*");var e,f,h=b.toLowerCase().split(Ka),g=0,j=h.length;if(u.d(c))for(;g<j;g++)e=h[g],(f=/^\+/.test(e))&&(e=e.substr(1)||"*"),e=a[e]=a[e]||[],e[f?"unshift":"push"](c)}}
function La(a,b,c,e,f,h){f=f||b.v[0];h=h||{};h[f]=d;var g;f=a[f];for(var j=0,k=f?f.length:0,l=a===Ma;j<k&&(l||!g);j++)g=f[j](b,c,e),"string"==typeof g&&(!l||h[g]?g=s:(b.v.unshift(g),g=La(a,b,c,e,g,h)));return(l||!g)&&!h["*"]&&(g=La(a,b,c,e,"*",h)),g}function Na(a,b){var c,e,f=u.P.Uc||{};for(c in b)b[c]!==s&&((f[c]?a:e||(e={}))[c]=b[c]);e&&u.extend(d,a,e)}function Oa(){try{return new r.XMLHttpRequest}catch(a){}}function Pa(){return setTimeout(function(){Qa=s},0),Qa=u.now()}
function Ra(a,b,c){function e(){for(var b=Qa||Pa(),b=Math.max(0,k.startTime+k.duration-b),c=1-(b/k.duration||0),e=0,f=k.xa.length;e<f;e++)k.xa[e].ic(c);return j.sd(a,[k,c,b]),1>c&&f?b:(j.ga(a,[k]),p)}var f,h=0,g=Sa.length,j=u.W().Q(function(){delete e.f}),k=j.m({f:a,M:u.extend({},b),o:u.extend(d,{mc:{}},c),lf:b,kf:c,startTime:Qa||Pa(),duration:c.duration,xa:[],Ib:function(b,c){var e=u.xc(a,k.o,b,c,k.o.mc[b]||k.o.oa);return k.xa.push(e),e},stop:function(b){for(var c=0,e=b?k.xa.length:0;c<e;c++)k.xa[c].ic(1);
return b?j.ga(a,[k,b]):j.Gd(a,[k,b]),this}});b=k.M;c=k.o.mc;var l,q,m,t;for(f in b)if(l=u.S(f),q=c[l],m=b[f],u.isArray(m)&&(q=m[1],m=b[f]=m[0]),f!==l&&(b[l]=m,delete b[f]),(t=u.p[l])&&"expand"in t)for(f in m=t.expand(m),delete b[l],m)f in b||(b[f]=m[f],c[f]=q);else c[l]=q;for(;h<g;h++)if(f=Sa[h].call(k,a,b,k.o))return f;var v=k;u.a(b,function(a,b){for(var c=(Ta[a]||[]).concat(Ta["*"]),e=0,f=c.length;e<f&&!c[e].call(v,a,b);e++);});return u.d(k.o.start)&&k.o.start.call(a,k),u.k.Ud(u.extend(e,{Bc:k,
j:k.o.j,f:a})),k.rb(k.o.rb).w(k.o.w,k.o.complete).qa(k.o.qa).Q(k.o.Q)}function D(a,b,c,e,f){return new D.prototype.z(a,b,c,e,f)}function Ua(a,b){var c,e={height:a},f=0;for(b=b?1:0;4>f;f+=2-b)c=Ba[f],e["margin"+c]=e["padding"+c]=a;return b&&(e.opacity=e.width=a),e}function Va(a){return u.U(a)?a:9===a.nodeType?a.defaultView||a.parentWindow:p}
var Wa,Ya,A=r.document,Za=r.location,$a=r.navigator,ab=r.Ha,bb=r.Qa,cb=Array.prototype.push,E=Array.prototype.slice,db=Array.prototype.indexOf,eb=Object.prototype.toString,fb=Object.prototype.hasOwnProperty,gb=String.prototype.trim;function u(a,b){return new u.b.z(a,b,Wa)}
var hb=/[\-+]?(?:\d*\.|)\d+(?:[eE][\-+]?\d+|)/.source,ib=/\S/,Ka=/\s+/,jb=/^[\s\uFEFF\xA0]+|[\s\uFEFF\xA0]+$/g,kb=/^(?:[^#<]*(<[\w\W]+>)[^>]*$|#([\w\-]*)$)/,lb=/^<(\w+)\s*\/?>(?:<\/\1>|)$/,mb=/^[\],:{}\s]*$/,nb=/(?:^|:|,)(?:\s*\[)+/g,ob=/\\(?:["\\\/bfnrt]|u[\da-fA-F]{4})/g,pb=/"[^"\\\r\n]*"|true|false|null|-?(?:\d\d*\.|)\d+(?:[eE][\-+]?\d+|)/g,qb=/^-ms-/,rb=/-([\da-z])/gi;function sb(a,b){return(b+"").toUpperCase()}
function tb(){A.addEventListener?(A.removeEventListener("DOMContentLoaded",tb,p),u.s()):"complete"===A.readyState&&(A.detachEvent("onreadystatechange",tb),u.s())}var ub={};
u.b=u.prototype={constructor:u,z:function(a,b,c){var e,f;if(!a)return this;if(a.nodeType)return this.u=this[0]=a,this.length=1,this;if("string"==typeof a){"<"===a.charAt(0)&&">"===a.charAt(a.length-1)&&3<=a.length?e=[n,a,n]:e=kb.exec(a);if(e&&(e[1]||!b)){if(e[1])return b=b instanceof u?b[0]:b,f=b&&b.nodeType?b.ownerDocument||b:A,a=u.vd(e[1],f,d),lb.test(e[1])&&u.Ea(b)&&this.H.call(a,b,d),u.A(this,a);if((b=A.getElementById(e[2]))&&b.parentNode){if(b.id!==e[2])return c.find(a);this.length=1;this[0]=
b}return this.u=A,this.i=a,this}return!b||b.Ia?(b||c).find(a):this.constructor(b).find(a)}return u.d(a)?c.s(a):(a.i!==s&&(this.i=a.i,this.u=a.u),u.ca(a,this))},i:"",Ia:"1.8.3",length:0,Vd:function(){return E.call(this)},get:function(a){return a==n?this.Vd():0>a?this[this.length+a]:this[a]},r:function(a,b,c){a=u.A(this.constructor(),a);return a.qb=this,a.u=this.u,"find"===b?a.i=this.i+(this.i?" ":"")+c:b&&(a.i=this.i+"."+b+"("+c+")"),a},a:function(a,b){return u.a(this,a,b)},s:function(a){return u.s.m().w(a),
this},pa:function(a){return a=+a,-1===a?this.slice(a):this.slice(a,a+1)},Aa:function(){return this.pa(0)},jd:function(){return this.pa(-1)},slice:function(){return this.r(E.apply(this,arguments),"slice",E.call(arguments).join(","))},map:function(a){return this.r(u.map(this,function(b,c){return a.call(b,c,b)}))},end:function(){return this.qb||this.constructor(n)},push:cb,sort:[].sort,splice:[].splice};u.b.z.prototype=u.b;
u.extend=u.b.extend=function(){var a,b,c,e,f,h,g=arguments[0]||{},j=1,k=arguments.length,l=p;"boolean"==typeof g&&(l=g,g=arguments[1]||{},j=2);"object"!=typeof g&&!u.d(g)&&(g={});for(k===j&&(g=this,--j);j<k;j++)if((a=arguments[j])!=n)for(b in a)c=g[b],e=a[b],g!==e&&(l&&e&&(u.Ea(e)||(f=u.isArray(e)))?(f?(f=p,h=c&&u.isArray(c)?c:[]):h=c&&u.Ea(c)?c:{},g[b]=u.extend(l,h,e)):e!==s&&(g[b]=e));return g};
u.extend({bf:function(a){return r.Qa===u&&(r.Qa=bb),a&&r.Ha===u&&(r.Ha=ab),u},ob:p,sb:1,Re:function(a){a?u.sb++:u.s(d)},s:function(a){if(!(a===d?--u.sb:u.ob)){if(!A.body)return setTimeout(u.s,1);u.ob=d;a!==d&&0<--u.sb||(Ya.ga(A,[u]),u.b.n&&u(A).n("ready").G("ready"))}},d:function(a){return"function"===u.type(a)},isArray:Array.isArray||function(a){return"array"===u.type(a)},U:function(a){return a!=n&&a==a.window},Tb:function(a){return!isNaN(parseFloat(a))&&isFinite(a)},type:function(a){return a==n?
String(a):ub[eb.call(a)]||"object"},Ea:function(a){if(!a||"object"!==u.type(a)||a.nodeType||u.U(a))return p;try{if(a.constructor&&!fb.call(a,"constructor")&&!fb.call(a.constructor.prototype,"isPrototypeOf"))return p}catch(b){return p}for(var c in a);return c===s||fb.call(a,c)},Da:function(a){for(var b in a)return p;return d},error:function(a){throw Error(a);},vd:function(a,b,c){var e;return!a||"string"!=typeof a?n:("boolean"==typeof b&&(c=b,b=0),b=b||A,(e=lb.exec(a))?[b.createElement(e[1])]:(e=u.Fb([a],
b,c?n:[]),u.A([],(e.Gb?u.Y(e.jb):e.jb).childNodes)))},cc:function(a){if(!a||"string"!=typeof a)return n;a=u.trim(a);if(r.JSON&&r.JSON.parse)return r.JSON.parse(a);if(mb.test(a.replace(ob,"@").replace(pb,"]").replace(nb,"")))return(new Function("return "+a))();u.error("Invalid JSON: "+a)},wd:function(a){var b,c;if(!a||"string"!=typeof a)return n;try{r.DOMParser?(c=new DOMParser,b=c.parseFromString(a,"text/xml")):(b=new ActiveXObject("Microsoft.XMLDOM"),b.async="false",b.loadXML(a))}catch(e){b=s}return(!b||
!b.documentElement||b.getElementsByTagName("parsererror").length)&&u.error("Invalid XML: "+a),b},Zb:function(){},Nb:function(a){a&&ib.test(a)&&(r.execScript||function(a){r.eval.call(r,a)})(a)},S:function(a){return a.replace(qb,"ms-").replace(rb,sb)},nodeName:function(a,b){return a.nodeName&&a.nodeName.toLowerCase()===b.toLowerCase()},a:function(a,b,c){var e,f=0,h=a.length,g=h===s||u.d(a);if(c)if(g)for(e in a){if(b.apply(a[e],c)===p)break}else for(;f<h&&b.apply(a[f++],c)!==p;);else if(g)for(e in a){if(b.call(a[e],
e,a[e])===p)break}else for(;f<h&&b.call(a[f],f,a[f++])!==p;);return a},trim:gb&&!gb.call("\ufeff\u00a0")?function(a){return a==n?"":gb.call(a)}:function(a){return a==n?"":(a+"").replace(jb,"")},ca:function(a,b){var c,e=b||[];return a!=n&&(c=u.type(a),a.length==n||"string"===c||"function"===c||"regexp"===c||u.U(a)?cb.call(e,a):u.A(e,a)),e},L:function(a,b,c){var e;if(b){if(db)return db.call(b,a,c);e=b.length;for(c=c?0>c?Math.max(0,e+c):c:0;c<e;c++)if(c in b&&b[c]===a)return c}return-1},A:function(a,
b){var c=b.length,e=a.length,f=0;if("number"==typeof c)for(;f<c;f++)a[e++]=b[f];else for(;b[f]!==s;)a[e++]=b[f++];return a.length=e,a},T:function(a,b,c){var e,f=[],h=0,g=a.length;for(c=!!c;h<g;h++)e=!!b(a[h],h),c!==e&&f.push(a[h]);return f},map:function(a,b,c){var e,f,h=[],g=0,j=a.length;if(a instanceof u||j!==s&&"number"==typeof j&&(0<j&&a[0]&&a[j-1]||0===j||u.isArray(a)))for(;g<j;g++)e=b(a[g],g,c),e!=n&&(h[h.length]=e);else for(f in a)e=b(a[f],f,c),e!=n&&(h[h.length]=e);return h.concat.apply([],
h)},h:1,tf:function(a,b){var c,e,f;return"string"==typeof b&&(c=a[b],b=a,a=c),u.d(a)?(e=E.call(arguments,2),f=function(){return a.apply(b,e.concat(E.call(arguments)))},f.h=a.h=a.h||u.h++,f):s},D:function(a,b,c,e,f,h,g){var j,k=c==n,l=0,q=a.length;if(c&&"object"==typeof c){for(l in c)u.D(a,b,l,c[l],1,h,e);f=1}else if(e!==s){j=g===s&&u.d(e);k&&(j?(j=b,b=function(a,b,c){return j.call(u(a),c)}):(b.call(a,e),b=n));if(b)for(;l<q;l++)b(a[l],c,j?e.call(a[l],l,b(a[l],c)):e,g);f=1}return f?a:k?b.call(a):q?
b(a[0],c):h},now:function(){return(new Date).getTime()}});u.s.m=function(a){if(!Ya)if(Ya=u.W(),"complete"===A.readyState)setTimeout(u.s,1);else if(A.addEventListener)A.addEventListener("DOMContentLoaded",tb,p),r.addEventListener("load",u.s,p);else{A.attachEvent("onreadystatechange",tb);r.attachEvent("onload",u.s);var b=p;try{b=r.frameElement==n&&A.documentElement}catch(c){}b&&b.doScroll&&function f(){if(!u.ob){try{b.doScroll("left")}catch(a){return setTimeout(f,50)}u.s()}}()}return Ya.m(a)};
u.a("Boolean Number String Function Array Date RegExp Object".split(" "),function(a,b){ub["[object "+b+"]"]=b.toLowerCase()});Wa=u(A);var vb={};
u.ha=function(a){function b(c){f=a.memory&&c;h=d;l=j||0;j=0;k=q.length;for(g=d;q&&l<k;l++)if(q[l].apply(c[0],c[1])===p&&a.Hf){f=p;break}g=p;q&&(m?m.length&&b(m.shift()):f?q=[]:t.disable())}var c;if("string"==typeof a){if(!(c=vb[a])){c=a;var e=vb[c]={};c=(u.a(c.split(Ka),function(a,b){e[b]=d}),e)}}else c=u.extend({},a);a=c;var f,h,g,j,k,l,q=[],m=!a.gf&&[],t={add:function(){if(q){var c=q.length;(function z(b){u.a(b,function(b,c){var e=u.type(c);"function"===e?(!a.unique||!t.kb(c))&&q.push(c):c&&c.length&&
"string"!==e&&z(c)})})(arguments);g?k=q.length:f&&(j=c,b(f))}return this},remove:function(){return q&&u.a(arguments,function(a,b){for(var c;-1<(c=u.L(b,q,c));)q.splice(c,1),g&&(c<=k&&k--,c<=l&&l--)}),this},kb:function(a){return-1<u.L(a,q)},empty:function(){return q=[],this},disable:function(){return q=m=f=s,this},disabled:function(){return!q},kd:function(){return m=s,f||t.disable(),this},Xe:function(){return!m},hb:function(a,c){return c=c||[],c=[a,c.slice?c.slice():c],q&&(!h||m)&&(g?m.push(c):b(c)),
this},ra:function(){return t.hb(this,arguments),this},Ke:function(){return!!h}};return t};
u.extend({W:function(a){var b=[["resolve","done",u.ha("once memory"),"resolved"],["reject","fail",u.ha("once memory"),"rejected"],["notify","progress",u.ha("memory")]],c="pending",e={state:function(){return c},Q:function(){return f.w(arguments).qa(arguments),this},Sd:function(){var a=arguments;return u.W(function(c){u.a(b,function(b,e){var l=e[0],q=a[b];f[e[1]](u.d(q)?function(){var a=q.apply(this,arguments);a&&u.d(a.m)?a.m().w(c.yf).qa(c.Fd).rb(c.cf):c[l+"With"](this===f?c:this,[a])}:c[l])});a=n}).m()},
m:function(a){return a!=n?u.extend(a,e):e}},f={};return e.of=e.Sd,u.a(b,function(a,g){var j=g[2],k=g[3];e[g[1]]=j.add;k&&j.add(function(){c=k},b[a^1][2].disable,b[2][2].kd);f[g[0]]=j.ra;f[g[0]+"With"]=j.hb}),e.m(f),a&&a.call(f,f),f},Wf:function(a){function b(a,b,c){return function(e){b[a]=this;c[a]=1<arguments.length?E.call(arguments):e;c===j?g.sd(b,c):--h||g.ga(b,c)}}var c=0,e=E.call(arguments),f=e.length,h=1!==f||a&&u.d(a.m)?f:0,g=1===h?a:u.W(),j,k,l;if(1<f){j=Array(f);k=Array(f);for(l=Array(f);c<
f;c++)e[c]&&u.d(e[c].m)?e[c].m().w(b(c,l,e)).qa(g.Fd).rb(b(c,k,j)):--h}return h||g.ga(l,e),g.m()}});var wb=u,xb;var G,yb,I,zb,Ab,L,Bb,Cb,Db,Eb,Fb,N=A.createElement("div");N.setAttribute("className","t");N.innerHTML="  <link/><table></table><a href='/a'>a</a><input type='checkbox'/>";yb=N.getElementsByTagName("*");I=N.getElementsByTagName("a")[0];
if(!yb||!I||!yb.length)xb={};else{zb=A.createElement("select");Ab=zb.appendChild(A.createElement("option"));L=N.getElementsByTagName("input")[0];I.style.cssText="top:1px;float:left;opacity:.5";G={Wb:3===N.firstChild.nodeType,qc:!N.getElementsByTagName("tbody").length,Qb:!!N.getElementsByTagName("link").length,style:/top/.test(I.getAttribute("style")),ad:"/a"===I.getAttribute("href"),opacity:/^0.5/.test(I.style.opacity),cssFloat:!!I.style.cssFloat,Lc:"on"===L.value,ud:Ab.selected,Xc:"t"!==N.className,
enctype:!!A.createElement("form").enctype,mb:"<:nav></:nav>"!==A.createElement("nav").cloneNode(d).outerHTML,ne:"CSS1Compat"===A.compatMode,Pd:d,Kc:d,Vc:p,eb:d,Yb:d,Rb:p,kc:p,fc:d,Eb:d,dc:p};L.checked=d;G.pd=L.cloneNode(d).checked;zb.disabled=d;G.td=!Ab.disabled;try{delete N.test}catch(Gb){G.eb=p}!N.addEventListener&&N.attachEvent&&N.fireEvent&&(N.attachEvent("onclick",Fb=function(){G.Yb=p}),N.cloneNode(d).fireEvent("onclick"),N.detachEvent("onclick",Fb));L=A.createElement("input");L.value="t";L.setAttribute("type",
"radio");G.Ed="t"===L.value;L.setAttribute("checked","checked");L.setAttribute("name","t");N.appendChild(L);Bb=A.createDocumentFragment();Bb.appendChild(N.lastChild);G.Hb=Bb.cloneNode(d).cloneNode(d).lastChild.checked;G.Cc=L.checked;Bb.removeChild(L);Bb.appendChild(N);if(N.attachEvent)for(Db in{submit:d,Jc:d,Le:d})Cb="on"+Db,(Eb=Cb in N)||(N.setAttribute(Cb,"return;"),Eb="function"==typeof N[Cb]),G[Db+"Bubbles"]=Eb;xb=(u(function(){var a,b,c,e,f=A.getElementsByTagName("body")[0];f&&(a=A.createElement("div"),
a.style.cssText="visibility:hidden;border:0;width:0;height:0;position:static;top:0;margin-top:1px",f.insertBefore(a,f.firstChild),b=A.createElement("div"),a.appendChild(b),b.innerHTML="<table><tr><td></td><td>t</td></tr></table>",c=b.getElementsByTagName("td"),c[0].style.cssText="padding:0;margin:0;border:0;display:none",Eb=0===c[0].offsetHeight,c[0].style.display="",c[1].style.display="none",G.Hd=Eb&&0===c[0].offsetHeight,b.innerHTML="",b.style.cssText="box-sizing:border-box;-moz-box-sizing:border-box;-webkit-box-sizing:border-box;padding:1px;border:1px;display:block;width:4px;margin-top:1%;position:absolute;top:1%;",
G.boxSizing=4===b.offsetWidth,G.Sc=1!==f.offsetTop,r.getComputedStyle&&(G.dc="1%"!==(r.getComputedStyle(b,n)||{}).top,G.Eb="4px"===(r.getComputedStyle(b,n)||{width:"4px"}).width,e=A.createElement("div"),e.style.cssText=b.style.cssText="padding:0;margin:0;border:0;display:block;overflow:hidden;",e.style.marginRight=e.style.width="0",b.style.width="1px",b.appendChild(e),G.fc=!parseFloat((r.getComputedStyle(e,n)||{}).marginRight)),"undefined"!=typeof b.style.zoom&&(b.innerHTML="",b.style.cssText="padding:0;margin:0;border:0;display:block;overflow:hidden;width:1px;padding:1px;display:inline;zoom:1",
G.Rb=3===b.offsetWidth,b.style.display="block",b.style.overflow="visible",b.innerHTML="<div></div>",b.firstChild.style.width="5px",G.kc=3!==b.offsetWidth,a.style.zoom=1),f.removeChild(a))}),Bb.removeChild(N),yb=I=zb=Ab=L=Bb=N=n,G)}wb.c=xb;var ca=/(?:\{[\s\S]*\}|\[[\s\S]*\])$/,ba=/([A-Z])/g;
u.extend({I:{},Jb:[],Vf:0,expando:"jQuery"+(u.b.Ia+Math.random()).replace(/\D/g,""),qd:{Ce:d,object:"clsid:D27CDB6E-AE6D-11cf-96B8-444553540000",je:d},Ob:function(a){return a=a.nodeType?u.I[a[u.expando]]:a[u.expando],!!a&&!ea(a)},data:function(a,b,c,e){if(u.ia(a)){var f,h,g=u.expando,j="string"==typeof b,k=a.nodeType,l=k?u.I:a,q=k?a[g]:a[g]&&g;if(q&&l[q]&&(e||l[q].data)||!(j&&c===s)){q||(k?a[g]=q=u.Jb.pop()||u.h++:q=g);l[q]||(l[q]={},k||(l[q].toJSON=u.Zb));if("object"==typeof b||"function"==typeof b)e?
l[q]=u.extend(l[q],b):l[q].data=u.extend(l[q].data,b);return f=l[q],e||(f.data||(f.data={}),f=f.data),c!==s&&(f[u.S(b)]=c),j?(h=f[b],h==n&&(h=f[u.S(b)])):h=f,h}}},fa:function(a,b,c){if(u.ia(a)){var e,f,h,g=a.nodeType,j=g?u.I:a,k=g?a[u.expando]:u.expando;if(j[k]){if(b&&(e=c?j[k]:j[k].data)){u.isArray(b)||(b in e?b=[b]:(b=u.S(b),b in e?b=[b]:b=b.split(" ")));f=0;for(h=b.length;f<h;f++)delete e[b[f]];if(!(c?ea:u.Da)(e))return}if(!c&&(delete j[k].data,!ea(j[k])))return;g?u.ja([a],d):u.c.eb||j!=j.window?
delete j[k]:j[k]=n}}},e:function(a,b,c){return u.data(a,b,c,d)},ia:function(a){var b=a.nodeName&&u.qd[a.nodeName.toLowerCase()];return!b||b!==d&&a.getAttribute("classid")===b}});
u.b.extend({data:function(a,b){var c,e,f,h,g,j=this[0],k=0,l=n;if(a===s){if(this.length&&(l=u.data(j),1===j.nodeType&&!u.e(j,"parsedAttrs"))){f=j.attributes;for(g=f.length;k<g;k++)h=f[k].name,h.indexOf("data-")||(h=u.S(h.substring(5)),aa(j,h,l[h]));u.e(j,"parsedAttrs",d)}return l}return"object"==typeof a?this.a(function(){u.data(this,a)}):(c=a.split(".",2),c[1]=c[1]?"."+c[1]:"",e=c[1]+"!",u.D(this,function(b){if(b===s)return l=this.ub("getData"+e,[c[0]]),l===s&&j&&(l=u.data(j,a),l=aa(j,a,l)),l===
s&&c[1]?this.data(c[0]):l;c[1]=b;this.a(function(){var f=u(this);f.ub("setData"+e,c);u.data(this,a,b);f.ub("changeData"+e,c)})},n,b,1<arguments.length,n,p))},fa:function(a){return this.a(function(){u.fa(this,a)})}});
u.extend({j:function(a,b,c){var e;if(a)return b=(b||"fx")+"queue",e=u.e(a,b),c&&(!e||u.isArray(c)?e=u.e(a,b,u.ca(c)):e.push(c)),e||[]},$:function(a,b){function c(){u.$(a,b)}b=b||"fx";var e=u.j(a,b),f=e.length,h=e.shift(),g=u.Ua(a,b);"inprogress"===h&&(h=e.shift(),f--);h&&("fx"===b&&e.unshift("inprogress"),delete g.stop,h.call(a,c,g));!f&&g&&g.empty.ra()},Ua:function(a,b){var c=b+"queueHooks";return u.e(a,c)||u.e(a,c,{empty:u.ha("once memory").add(function(){u.fa(a,b+"queue",d);u.fa(a,c,d)})})}});
u.b.extend({j:function(a,b){var c=2;return"string"!=typeof a&&(b=a,a="fx",c--),arguments.length<c?u.j(this[0],a):b===s?this:this.a(function(){var c=u.j(this,a,b);u.Ua(this,a);"fx"===a&&"inprogress"!==c[0]&&u.$(this,a)})},$:function(a){return this.a(function(){u.$(this,a)})},ze:function(a,b){return a=u.k?u.k.Na[a]||a:a,b=b||"fx",this.j(b,function(b,e){var f=setTimeout(b,a);e.stop=function(){clearTimeout(f)}})},te:function(a){return this.j(a||"fx",[])},m:function(a,b){function c(){--f||h.ga(g,[g])}
var e,f=1,h=u.W(),g=this,j=this.length;"string"!=typeof a&&(b=a,a=s);for(a=a||"fx";j--;)(e=u.e(g[j],a+"queueHooks"))&&e.empty&&(f++,e.empty.add(c));return c(),h.m(b)}});var O,Hb,Ib,Jb=/[\t\r\n]/g,Kb=/\r/g,Lb=/^(?:button|input)$/i,Mb=/^(?:button|input|object|select|textarea)$/i,Nb=/^a(?:rea|)$/i,Ob=/^(?:autofocus|autoplay|async|checked|controls|defer|disabled|hidden|loop|multiple|open|readonly|required|scoped|selected)$/i,Pb=u.c.Xc;
u.b.extend({H:function(a,b){return u.D(this,u.H,a,b,1<arguments.length)},La:function(a){return this.a(function(){u.La(this,a)})},l:function(a,b){return u.D(this,u.l,a,b,1<arguments.length)},wf:function(a){return a=u.ua[a]||a,this.a(function(){try{this[a]=s,delete this[a]}catch(b){}})},zc:function(a){var b,c,e,f,h,g,j;if(u.d(a))return this.a(function(b){u(this).zc(a.call(this,b,this.className))});if(a&&"string"==typeof a){b=a.split(Ka);c=0;for(e=this.length;c<e;c++)if(f=this[c],1===f.nodeType)if(!f.className&&
1===b.length)f.className=a;else{h=" "+f.className+" ";g=0;for(j=b.length;g<j;g++)0>h.indexOf(" "+b[g]+" ")&&(h+=b[g]+" ");f.className=u.trim(h)}}return this},Id:function(a){var b,c,e,f,h,g,j;if(u.d(a))return this.a(function(b){u(this).Id(a.call(this,b,this.className))});if(a&&"string"==typeof a||a===s){b=(a||"").split(Ka);g=0;for(j=this.length;g<j;g++)if(e=this[g],1===e.nodeType&&e.className){c=(" "+e.className+" ").replace(Jb," ");f=0;for(h=b.length;f<h;f++)for(;0<=c.indexOf(" "+b[f]+" ");)c=c.replace(" "+
b[f]+" "," ");e.className=a?u.trim(c):""}}return this},Wd:function(a,b){var c=typeof a,e="boolean"==typeof b;return u.d(a)?this.a(function(c){u(this).Wd(a.call(this,c,this.className,b),b)}):this.a(function(){if("string"===c)for(var f,h=0,g=u(this),j=b,k=a.split(Ka);f=k[h++];)j=e?j:!g.Zc(f),g[j?"addClass":"removeClass"](f);else if("undefined"===c||"boolean"===c)this.className&&u.e(this,"__className__",this.className),this.className=this.className||a===p?"":u.e(this,"__className__")||""})},Zc:function(a){a=
" "+a+" ";for(var b=0,c=this.length;b<c;b++)if(1===this[b].nodeType&&0<=(" "+this[b].className+" ").replace(Jb," ").indexOf(a))return d;return p},ya:function(a){var b,c,e,f=this[0];if(arguments.length)return e=u.d(a),this.a(function(c){var f,j=u(this);if(1===this.nodeType&&(e?f=a.call(this,c,j.ya()):f=a,f==n?f="":"number"==typeof f?f+="":u.isArray(f)&&(f=u.map(f,function(a){return a==n?"":a+""})),b=u.N[this.type]||u.N[this.nodeName.toLowerCase()],!b||!("set"in b)||b.set(this,f,"value")===s))this.value=
f});if(f)return b=u.N[f.type]||u.N[f.nodeName.toLowerCase()],b&&"get"in b&&(c=b.get(f,"value"))!==s?c:(c=f.value,"string"==typeof c?c.replace(Kb,""):c==n?"":c)}});
u.extend({N:{ac:{get:function(a){var b=a.attributes.value;return!b||b.specified?a.value:a.text}},select:{get:function(a){for(var b,c=a.options,e=a.selectedIndex,f=(a="select-one"===a.type||0>e)?n:[],h=a?e+1:c.length,g=0>e?h:a?e:0;g<h;g++)if(b=c[g],(b.selected||g===e)&&(u.c.td?!b.disabled:b.getAttribute("disabled")===n)&&(!b.parentNode.disabled||!u.nodeName(b.parentNode,"optgroup"))){b=u(b).ya();if(a)return b;f.push(b)}return f},set:function(a,b){var c=u.ca(b);return u(a).find("option").a(function(){this.selected=
0<=u.L(u(this).ya(),c)}),c.length||(a.selectedIndex=-1),c}}},le:{},H:function(a,b,c,e){var f,h,g=a.nodeType;if(a&&!(3===g||8===g||2===g)){if(e&&u.d(u.b[b]))return u(a)[b](c);if("undefined"==typeof a.getAttribute)return u.l(a,b,c);(e=1!==g||!u.Ga(a))&&(b=b.toLowerCase(),h=u.R[b]||(Ob.test(b)?Hb:O));if(c!==s){if(c===n){u.La(a,b);return}return h&&"set"in h&&e&&(f=h.set(a,c,b))!==s?f:(a.setAttribute(b,c+""),c)}return h&&"get"in h&&e&&(f=h.get(a,b))!==n?f:(f=a.getAttribute(b),f===n?s:f)}},La:function(a,
b){var c,e,f,h,g=0;if(b&&1===a.nodeType)for(e=b.split(Ka);g<e.length;g++)(f=e[g])&&(c=u.ua[f]||f,h=Ob.test(f),h||u.H(a,f,""),a.removeAttribute(Pb?f:c),h&&c in a&&(a[c]=p))},R:{type:{set:function(a,b){if(Lb.test(a.nodeName)&&a.parentNode)u.error("type property can't be changed");else if(!u.c.Ed&&"radio"===b&&u.nodeName(a,"input")){var c=a.value;return a.setAttribute("type",b),c&&(a.value=c),b}}},value:{get:function(a,b){return O&&u.nodeName(a,"button")?O.get(a,b):b in a?a.value:n},set:function(a,b,
c){if(O&&u.nodeName(a,"button"))return O.set(a,b,c);a.value=b}}},ua:{Kf:"tabIndex",vf:"readOnly","for":"htmlFor","class":"className",Ze:"maxLength",pe:"cellSpacing",oe:"cellPadding",zf:"rowSpan",xe:"colSpan",Tf:"useMap",Me:"frameBorder",Nc:"contentEditable"},l:function(a,b,c){var e,f,h,g=a.nodeType;if(a&&!(3===g||8===g||2===g))return h=1!==g||!u.Ga(a),h&&(b=u.ua[b]||b,f=u.B[b]),c!==s?f&&"set"in f&&(e=f.set(a,c,b))!==s?e:a[b]=c:f&&"get"in f&&(e=f.get(a,b))!==n?e:a[b]},B:{tabIndex:{get:function(a){var b=
a.getAttributeNode("tabindex");return b&&b.specified?parseInt(b.value,10):Mb.test(a.nodeName)||Nb.test(a.nodeName)&&a.href?0:s}}}});Hb={get:function(a,b){var c,e=u.l(a,b);return e===d||"boolean"!=typeof e&&(c=a.getAttributeNode(b))&&c.nodeValue!==p?b.toLowerCase():s},set:function(a,b,c){var e;return b===p?u.La(a,c):(e=u.ua[c]||c,e in a&&(a[e]=d),a.setAttribute(c,c.toLowerCase())),c}};
Pb||(Ib={name:d,id:d,coords:d},O=u.N.button={get:function(a,b){var c;return c=a.getAttributeNode(b),c&&(Ib[b]?""!==c.value:c.specified)?c.value:s},set:function(a,b,c){var e=a.getAttributeNode(c);return e||(e=A.createAttribute(c),a.setAttributeNode(e)),e.value=b+""}},u.a(["width","height"],function(a,b){u.R[b]=u.extend(u.R[b],{set:function(a,e){if(""===e)return a.setAttribute(b,"auto"),e}})}),u.R.Nc={get:O.get,set:function(a,b,c){""===b&&(b="false");O.set(a,b,c)}});
u.c.ad||u.a(["href","src","width","height"],function(a,b){u.R[b]=u.extend(u.R[b],{get:function(a){a=a.getAttribute(b,2);return a===n?s:a}})});u.c.style||(u.R.style={get:function(a){return a.style.cssText.toLowerCase()||s},set:function(a,b){return a.style.cssText=b+""}});u.c.ud||(u.B.selected=u.extend(u.B.selected,{get:function(a){a=a.parentNode;return a&&(a.selectedIndex,a.parentNode&&a.parentNode.selectedIndex),n}}));u.c.enctype||(u.ua.enctype="encoding");
u.c.Lc||u.a(["radio","checkbox"],function(){u.N[this]={get:function(a){return a.getAttribute("value")===n?"on":a.value}}});u.a(["radio","checkbox"],function(){u.N[this]=u.extend(u.N[this],{set:function(a,b){if(u.isArray(b))return a.checked=0<=u.L(u(a).ya(),b)}})});var Qb=/^(?:textarea|input|select)$/i,Rb=/^([^\.]*|)(?:\.(.+)|)$/,Sb=/(?:^|\s)hover(\.\S+|)\b/,Tb=/^key/,Ub=/^(?:mouse|contextmenu)|click/,Vb=/^(?:focusinfocus|focusoutblur)$/;
function Wb(a){return u.event.t.$c?a:a.replace(Sb,"mouseenter$1 mouseleave$1")}
u.event={add:function(a,b,c,e,f){var h,g,j,k,l,q,m,t,v;if(!(3===a.nodeType||8===a.nodeType||!b||!c||!(h=u.e(a)))){c.K&&(m=c,c=m.K,f=m.i);c.h||(c.h=u.h++);(j=h.J)||(h.J=j={});(g=h.handle)||(h.handle=g=function(a){return"undefined"==typeof u||a&&u.event.vb===a.type?s:u.event.fb.apply(g.f,arguments)},g.f=a);b=u.trim(Wb(b)).split(" ");for(h=0;h<b.length;h++){k=Rb.exec(b[h])||[];l=k[1];q=(k[2]||"").split(".").sort();v=u.event.t[l]||{};l=(f?v.na:v.Ya)||l;v=u.event.t[l]||{};k=u.extend({type:l,ta:k[1],data:e,
K:c,h:c.h,i:f,Ja:f&&u.q.match.Ja.test(f),F:q.join(".")},m);t=j[l];if(!t&&(t=j[l]=[],t.cb=0,!v.va||v.va.call(a,e,q,g)===p))a.addEventListener?a.addEventListener(l,g,p):a.attachEvent&&a.attachEvent("on"+l,g);v.add&&(v.add.call(a,k),k.K.h||(k.K.h=c.h));f?t.splice(t.cb++,0,k):t.push(k);u.event.global[l]=d}a=n}},global:{},remove:function(a,b,c,e,f){var h,g,j,k,l,q,m,t,v,B,z=u.Ob(a)&&u.e(a);if(z&&(m=z.J)){b=u.trim(Wb(b||"")).split(" ");for(h=0;h<b.length;h++)if(g=Rb.exec(b[h])||[],j=k=g[1],g=g[2],j){t=
u.event.t[j]||{};j=(e?t.na:t.Ya)||j;v=m[j]||[];l=v.length;g=g?RegExp("(^|\\.)"+g.split(".").sort().join("\\.(?:.*\\.|)")+"(\\.|$)"):n;for(q=0;q<v.length;q++)B=v[q],(f||k===B.ta)&&(!c||c.h===B.h)&&(!g||g.test(B.F))&&(!e||e===B.i||"**"===e&&B.i)&&(v.splice(q--,1),B.i&&v.cb--,t.remove&&t.remove.call(a,B));0===v.length&&l!==v.length&&((!t.wa||t.wa.call(a,g,z.handle)===p)&&u.gc(a,j,z.handle),delete m[j])}else for(j in m)u.event.remove(a,j+b[h],c,e,d);u.Da(m)&&(delete z.handle,u.fa(a,"events",d))}},Pc:{getData:d,
setData:d,qe:d},n:function(a,b,c,e){if(!c||3!==c.nodeType&&8!==c.nodeType){var f,h,g,j,k,l,q,m=a.type||a;j=[];if(!Vb.test(m+u.event.vb)&&(0<=m.indexOf("!")&&(m=m.slice(0,-1),f=d),0<=m.indexOf(".")&&(j=m.split("."),m=j.shift(),j.sort()),c&&!u.event.Pc[m]||u.event.global[m]))if(a="object"==typeof a?a[u.expando]?a:new u.O(m,a):new u.O(m),a.type=m,a.Fa=d,a.Tc=f,a.F=j.join("."),a.Xb=a.F?RegExp("(^|\\.)"+j.join("\\.(?:.*\\.|)")+"(\\.|$)"):n,j=0>m.indexOf(":")?"on"+m:"",c){if(a.result=s,a.target||(a.target=
c),b=b!=n?u.ca(b):[],b.unshift(a),k=u.event.t[m]||{},!(k.n&&k.n.apply(c,b)===p)){q=[[c,k.Ya||m]];if(!e&&!k.od&&!u.U(c)){h=k.na||m;f=Vb.test(h+m)?c:c.parentNode;for(g=c;f;f=f.parentNode)q.push([f,h]),g=f;g===(c.ownerDocument||A)&&q.push([g.defaultView||g.parentWindow||r,h])}for(h=0;h<q.length&&!a.nb();h++)f=q[h][0],a.type=q[h][1],(l=(u.e(f,"events")||{})[a.type]&&u.e(f,"handle"))&&l.apply(f,b),(l=j&&f[j])&&u.ia(f)&&l.apply&&l.apply(f,b)===p&&a.preventDefault();return a.type=m,!e&&!a.Ca()&&(!k.C||k.C.apply(c.ownerDocument,
b)===p)&&("click"!==m||!u.nodeName(c,"a"))&&u.ia(c)&&j&&c[m]&&("focus"!==m&&"blur"!==m||0!==a.target.offsetWidth)&&!u.U(c)&&(g=c[j],g&&(c[j]=n),u.event.vb=m,c[m](),u.event.vb=s,g&&(c[j]=g)),a.result}}else for(h in c=u.I,c)c[h].J&&c[h].J[m]&&u.event.n(a,b,c[h].handle.f,d)}},fb:function(a){a=u.event.Lb(a||r.event);var b,c,e,f,h,g,j=(u.e(this,"events")||{})[a.type]||[],k=j.cb,l=E.call(arguments),q=!a.Tc&&!a.F,m=u.event.t[a.type]||{},t=[];l[0]=a;a.Rc=this;if(!(m.zd&&m.zd.call(this,a)===p)){if(k&&(!a.button||
"click"!==a.type))for(c=a.target;c!=this;c=c.parentNode||this)if(c.disabled!==d||"click"!==a.type){f={};h=[];for(b=0;b<k;b++)e=j[b],g=e.i,f[g]===s&&(f[g]=e.Ja?0<=u(g,this).index(c):u.find(g,this,n,[c]).length),f[g]&&h.push(e);h.length&&t.push({f:c,matches:h})}j.length>k&&t.push({f:this,matches:j.slice(k)});for(b=0;b<t.length&&!a.nb();b++){f=t[b];a.currentTarget=f.f;for(c=0;c<f.matches.length&&!a.ed();c++)if(e=f.matches[c],q||!a.F&&!e.F||a.Xb&&a.Xb.test(e.F))a.data=e.data,a.Ba=e,e=((u.event.t[e.ta]||
{}).handle||e.K).apply(f.f,l),e!==s&&(a.result=e,e===p&&(a.preventDefault(),a.stopPropagation()))}return m.ec&&m.ec.call(this,a),a.result}},M:"attrChange attrName relatedNode srcElement altKey bubbles cancelable ctrlKey currentTarget eventPhase metaKey relatedTarget shiftKey target timeStamp view which".split(" "),ib:{},hd:{M:["char","charCode","key","keyCode"],filter:function(a,b){return a.which==n&&(a.which=b.charCode!=n?b.charCode:b.keyCode),a}},ld:{M:"button buttons clientX clientY fromElement offsetX offsetY pageX pageY screenX screenY toElement".split(" "),
filter:function(a,b){var c,e,f,h=b.button,g=b.fromElement;return a.pageX==n&&b.clientX!=n&&(c=a.target.ownerDocument||A,e=c.documentElement,f=c.body,a.pageX=b.clientX+(e&&e.scrollLeft||f&&f.scrollLeft||0)-(e&&e.clientLeft||f&&f.clientLeft||0),a.pageY=b.clientY+(e&&e.scrollTop||f&&f.scrollTop||0)-(e&&e.clientTop||f&&f.clientTop||0)),!a.relatedTarget&&g&&(a.relatedTarget=g===a.target?b.toElement:g),!a.which&&h!==s&&(a.which=h&1?1:h&2?3:h&4?2:0),a}},Lb:function(a){if(a[u.expando])return a;var b,c,e=
a,f=u.event.ib[a.type]||{},h=f.M?this.M.concat(f.M):this.M;a=u.O(e);for(b=h.length;b;)c=h[--b],a[c]=e[c];return a.target||(a.target=e.srcElement||A),3===a.target.nodeType&&(a.target=a.target.parentNode),a.metaKey=!!a.metaKey,f.filter?f.filter(a,e):a},t:{load:{od:d},focus:{na:"focusin"},blur:{na:"focusout"},me:{va:function(a,b,c){u.U(this)&&(this.onbeforeunload=c)},wa:function(a,b){this.onbeforeunload===b&&(this.onbeforeunload=n)}}},Ma:function(a,b,c,e){a=u.extend(new u.O,c,{type:a,Ub:d,Ka:{}});e?
u.event.n(a,n,b):u.event.fb.call(b,a);a.Ca()&&c.preventDefault()}};u.event.handle=u.event.fb;u.gc=A.removeEventListener?function(a,b,c){a.removeEventListener&&a.removeEventListener(b,c,p)}:function(a,b,c){b="on"+b;a.detachEvent&&("undefined"==typeof a[b]&&(a[b]=n),a.detachEvent(b,c))};
u.O=function(a,b){if(!(this instanceof u.O))return new u.O(a,b);a&&a.type?(this.Ka=a,this.type=a.type,this.Ca=a.defaultPrevented||a.returnValue===p||a.Wc&&a.Wc()?ga:fa):this.type=a;b&&u.extend(this,b);this.timeStamp=a&&a.timeStamp||u.now();this[u.expando]=d};
u.O.prototype={preventDefault:function(){this.Ca=ga;var a=this.Ka;a&&(a.preventDefault?a.preventDefault():a.returnValue=p)},stopPropagation:function(){this.nb=ga;var a=this.Ka;a&&(a.stopPropagation&&a.stopPropagation(),a.cancelBubble=d)},Ca:fa,nb:fa,ed:fa};u.a({md:"mouseover",nd:"mouseout"},function(a,b){u.event.t[a]={na:b,Ya:b,handle:function(a){var e,f=a.relatedTarget,h=a.Ba;if(!f||f!==this&&!u.contains(this,f))a.type=h.ta,e=h.K.apply(this,arguments),a.type=b;return e}}});
u.c.Pd||(u.event.t.submit={va:function(){if(u.nodeName(this,"form"))return p;u.event.add(this,"click._submit keypress._submit",function(a){a=a.target;(a=u.nodeName(a,"input")||u.nodeName(a,"button")?a.form:s)&&!u.e(a,"_submit_attached")&&(u.event.add(a,"submit._submit",function(a){a.Bb=d}),u.e(a,"_submit_attached",d))})},ec:function(a){a.Bb&&(delete a.Bb,this.parentNode&&!a.Fa&&u.event.Ma("submit",this.parentNode,a,d))},wa:function(){if(u.nodeName(this,"form"))return p;u.event.remove(this,"._submit")}});
u.c.Kc||(u.event.t.Jc={va:function(){if(Qb.test(this.nodeName)){if("checkbox"===this.type||"radio"===this.type)u.event.add(this,"propertychange._change",function(a){"checked"===a.Ka.propertyName&&(this.Ab=d)}),u.event.add(this,"click._change",function(a){this.Ab&&!a.Fa&&(this.Ab=p);u.event.Ma("change",this,a,d)});return p}u.event.add(this,"beforeactivate._change",function(a){a=a.target;Qb.test(a.nodeName)&&!u.e(a,"_change_attached")&&(u.event.add(a,"change._change",function(a){this.parentNode&&!a.Ub&&
!a.Fa&&u.event.Ma("change",this.parentNode,a,d)}),u.e(a,"_change_attached",d))})},handle:function(a){var b=a.target;if(this!==b||a.Ub||a.Fa||"radio"!==b.type&&"checkbox"!==b.type)return a.Ba.K.apply(this,arguments)},wa:function(){return u.event.remove(this,"._change"),!Qb.test(this.nodeName)}});
u.c.Vc||u.a({focus:"focusin",blur:"focusout"},function(a,b){function c(a){u.event.Ma(b,a.target,u.event.Lb(a),d)}var e=0;u.event.t[b]={va:function(){0===e++&&A.addEventListener(a,c,d)},wa:function(){0===--e&&A.removeEventListener(a,c,d)}}});
u.b.extend({V:function(a,b,c,e,f){var h,g;if("object"==typeof a){"string"!=typeof b&&(c=c||b,b=s);for(g in a)this.V(g,b,c,a[g],f);return this}c==n&&e==n?(e=b,c=b=s):e==n&&("string"==typeof b?(e=c,c=s):(e=c,c=b,b=s));if(e===p)e=fa;else if(!e)return this;return 1===f&&(h=e,e=function(a){return u().G(a),h.apply(this,arguments)},e.h=h.h||(h.h=u.h++)),this.a(function(){u.event.add(this,a,e,c,b)})},hf:function(a,b,c,e){return this.V(a,b,c,e,1)},G:function(a,b,c){var e,f;if(a&&a.preventDefault&&a.Ba)return e=
a.Ba,u(a.Rc).G(e.F?e.ta+"."+e.F:e.ta,e.i,e.K),this;if("object"==typeof a){for(f in a)this.G(f,b,a[f]);return this}if(b===p||"function"==typeof b)c=b,b=s;return c===p&&(c=fa),this.a(function(){u.event.remove(this,a,c,b)})},bind:function(a,b,c){return this.V(a,n,b,c)},Pf:function(a,b){return this.G(a,n,b)},We:function(a,b,c){return u(this.u).V(a,this.i,b,c),this},Be:function(a,b){return u(this.u).G(a,this.i||"**",b),this},Ae:function(a,b,c,e){return this.V(b,a,c,e)},Qf:function(a,b,c){return 1===arguments.length?
this.G(a,"**"):this.G(b,a||"**",c)},n:function(a,b){return this.a(function(){u.event.n(a,b,this)})},ub:function(a,b){if(this[0])return u.event.n(a,b,this[0],d)},toggle:function(a){function b(b){var e=(u.e(this,"lastToggle"+a.h)||0)%f;return u.e(this,"lastToggle"+a.h,e+1),b.preventDefault(),c[e].apply(this,arguments)||p}var c=arguments,e=a.h||u.h++,f=0;for(b.h=e;f<c.length;)c[f++].h=e;return this.click(b)},$c:function(a,b){return this.md(a).nd(b||a)}});
u.a("blur focus focusin focusout load resize scroll unload click dblclick mousedown mouseup mousemove mouseover mouseout mouseenter mouseleave change select submit keydown keypress keyup error contextmenu".split(" "),function(a,b){u.b[b]=function(a,e){return e==n&&(e=a,a=n),0<arguments.length?this.V(b,n,a,e):this.n(b)};Tb.test(b)&&(u.event.ib[b]=u.event.hd);Ub.test(b)&&(u.event.ib[b]=u.event.ld)});
function P(a,b,c,e){c=c||[];b=b||R;var f,h,g,j,k=b.nodeType;if(!a||"string"!=typeof a)return c;if(1!==k&&9!==k)return[];g=Xb(b);if(!g&&!e&&(f=Yb.exec(a)))if(j=f[1])if(9===k){h=b.getElementById(j);if(!h||!h.parentNode)return c;if(h.id===j)return c.push(h),c}else{if(b.ownerDocument&&(h=b.ownerDocument.getElementById(j))&&Zb(b,h)&&h.id===j)return c.push(h),c}else{if(f[2])return $b.apply(c,ac.call(b.getElementsByTagName(a),0)),c;if((j=f[3])&&bc&&b.getElementsByClassName)return $b.apply(c,ac.call(b.getElementsByClassName(j),
0)),c}return cc(a.replace(dc,"$1"),b,c,e,g)}function ec(a){return function(b){return"input"===b.nodeName.toLowerCase()&&b.type===a}}function fc(a){return function(b){var c=b.nodeName.toLowerCase();return("input"===c||"button"===c)&&b.type===a}}function gc(a){return S(function(b){return b=+b,S(function(c,e){for(var f,h=a([],c.length,b),g=h.length;g--;)c[f=h[g]]&&(c[f]=!(e[f]=c[f]))})})}function hc(a,b,c){if(a===b)return c;for(a=a.nextSibling;a;){if(a===b)return-1;a=a.nextSibling}return 1}
function ic(a,b){var c,e,f,h,g,j,k;if(g=jc[V][a+" "])return b?0:g.slice(0);g=a;j=[];for(k=W.Ad;g;){if(!c||(e=kc.exec(g)))e&&(g=g.slice(e[0].length)||g),j.push(f=[]);c=p;if(e=lc.exec(g))f.push(c=new mc(e.shift())),g=g.slice(c.length),c.type=e[0].replace(dc," ");for(h in W.filter)(e=nc[h].exec(g))&&(!k[h]||(e=k[h](e)))&&(f.push(c=new mc(e.shift())),g=g.slice(c.length),c.type=h,c.matches=e);if(!c)break}return b?g.length:g?P.error(a):jc(a,j).slice(0)}
function oc(a,b,c){var e=b.dir,f=c&&"parentNode"===b.dir,h=pc++;return b.Aa?function(b,c,h){for(;b=b[e];)if(f||1===b.nodeType)return a(b,c,h)}:function(b,c,k){if(k)for(;b=b[e];){if((f||1===b.nodeType)&&a(b,c,k))return b}else for(var l,q=qc+" "+h+" ",m=q+rc;b=b[e];)if(f||1===b.nodeType){if((l=b[V])===m)return b.tb;if("string"==typeof l&&0===l.indexOf(q)){if(b.tb)return b}else{b[V]=m;if(a(b,c,k))return b.tb=d,b;b.tb=p}}}}
function sc(a){return 1<a.length?function(b,c,e){for(var f=a.length;f--;)if(!a[f](b,c,e))return p;return d}:a[0]}function tc(a,b,c,e,f){for(var h,g=[],j=0,k=a.length,l=b!=n;j<k;j++)if(h=a[j])if(!c||c(h,e,f))g.push(h),l&&b.push(j);return g}
function uc(a,b,c,e,f,h){return e&&!e[V]&&(e=uc(e)),f&&!f[V]&&(f=uc(f,h)),S(function(g,h,k,l){var q,m,t=[],v=[],B=h.length,z;if(!(z=g)){z=b||"*";for(var y=k.nodeType?[k]:k,F=[],C=0,H=y.length;C<H;C++)P(z,y[C],F);z=F}z=a&&(g||!b)?tc(z,t,a,k,l):z;y=c?f||(g?a:B||e)?[]:h:z;c&&c(z,y,k,l);if(e){q=tc(y,v);e(q,[],k,l);for(k=q.length;k--;)if(m=q[k])y[v[k]]=!(z[v[k]]=m)}if(g){if(f||a){if(f){q=[];for(k=y.length;k--;)(m=y[k])&&q.push(z[k]=m);f(n,y=[],q,l)}for(k=y.length;k--;)(m=y[k])&&-1<(q=f?vc.call(g,m):t[k])&&
(g[q]=!(h[q]=m))}}else y=tc(y===h?y.splice(B,y.length):y),f?f(n,h,y,l):$b.apply(h,y)})}
function wc(a){var b,c,e,f=a.length,h=W.ea[a[0].type];c=h||W.ea[" "];for(var g=h?1:0,j=oc(function(a){return a===b},c,d),k=oc(function(a){return-1<vc.call(b,a)},c,d),l=[function(a,c,e){return!h&&(e||c!==xc)||((b=c).nodeType?j(a,c,e):k(a,c,e))}];g<f;g++)if(c=W.ea[a[g].type])l=[oc(sc(l),c)];else{c=W.filter[a[g].type].apply(n,a[g].matches);if(c[V]){for(e=++g;e<f&&!W.ea[a[e].type];e++);return uc(1<g&&sc(l),1<g&&a.slice(0,g-1).join("").replace(dc,"$1"),c,g<e&&wc(a.slice(g,e)),e<f&&wc(a=a.slice(e)),e<f&&
a.join(""))}l.push(c)}return sc(l)}
function cc(a,b,c,e,f){var h,g,j,k,l=ic(a);if(!e&&1===l.length){g=l[0]=l[0].slice(0);if(2<g.length&&"ID"===(j=g[0]).type&&9===b.nodeType&&!f&&W.ea[g[1].type]){b=W.find.Sa(j.matches[0].replace(yc,""),b,f)[0];if(!b)return c;a=a.slice(g.shift().length)}for(h=nc.wc.test(a)?-1:g.length-1;0<=h;h--){j=g[h];if(W.ea[k=j.type])break;if(k=W.find[k])if(e=k(j.matches[0].replace(yc,""),zc.test(g[0].type)&&b.parentNode||b,f)){g.splice(h,1);a=e.length&&g.join("");if(!a)return $b.apply(c,ac.call(e,0)),c;break}}}return Ac(a,
l)(e,b,f,c,zc.test(a)),c}function Bc(){}var rc,Cc,W,Dc,Xb,Zb,Ac,Ec,Fc,xc,Gc=d,V=("sizcache"+Math.random()).replace(".",""),mc=String,R=r.document,Z=R.documentElement,qc=0,pc=0,Hc=[].pop,$b=[].push,ac=[].slice,vc=[].indexOf||function(a){for(var b=0,c=this.length;b<c;b++)if(this[b]===a)return b;return-1};function S(a,b){return a[V]=b==n||b,a}function Ic(){var a={},b=[];return S(function(c,e){return b.push(c)>W.Ic&&delete a[b.shift()],a[c+" "]=e},a)}
var Jc=Ic(),jc=Ic(),Kc=Ic(),Lc="\\[[\\x20\\t\\r\\n\\f]*((?:\\\\.|[-\\w]|[^\\x00-\\xa0])+)[\\x20\\t\\r\\n\\f]*(?:([*^$|!~]?=)[\\x20\\t\\r\\n\\f]*(?:(['\"])((?:\\\\.|[^\\\\])*?)\\3|("+"(?:\\\\.|[-\\w]|[^\\x00-\\xa0])+".replace("w","w#")+")|)|)[\\x20\\t\\r\\n\\f]*\\]",Mc=":((?:\\\\.|[-\\w]|[^\\x00-\\xa0])+)(?:\\((?:(['\"])((?:\\\\.|[^\\\\])*?)\\2|([^()[\\]]*|(?:(?:"+Lc+")|[^:]|\\\\.)*|.*))\\)|)",dc=/^[\x20\t\r\n\f]+|((?:^|[^\\])(?:\\.)*)[\x20\t\r\n\f]+$/g,kc=/^[\x20\t\r\n\f]*,[\x20\t\r\n\f]*/,lc=/^[\x20\t\r\n\f]*([\x20\t\r\n\f>+~])[\x20\t\r\n\f]*/,
Nc=RegExp(Mc),Yb=/^(?:#([\w\-]+)|(\w+)|\.([\w\-]+))$/,zc=/[\x20\t\r\n\f]*[+~]/,Oc=/h\d/i,Pc=/input|select|textarea|button/i,yc=/\\(?!\\)/g,nc={Sa:/^#((?:\\.|[-\w]|[^\x00-\xa0])+)/,yb:/^\.((?:\\.|[-\w]|[^\x00-\xa0])+)/,vc:/^\[name=['"]?((?:\\.|[-\w]|[^\x00-\xa0])+)['"]?\]/,Ta:RegExp("^("+"(?:\\\\.|[-\\w]|[^\\x00-\\xa0])+".replace("w","w*")+")"),xb:RegExp("^"+Lc),zb:RegExp("^"+Mc),wc:/:(even|odd|eq|gt|lt|nth|first|last)(?:\([\x20\t\r\n\f]*((?:-\d)?\d*)[\x20\t\r\n\f]*\)|)(?=[^-]|$)/i,Ra:RegExp("^:(only|nth|first|last)-child(?:\\([\\x20\\t\\r\\n\\f]*(even|odd|(([+-]|)(\\d*)n|)[\\x20\\t\\r\\n\\f]*(?:([+-]|)[\\x20\\t\\r\\n\\f]*(\\d+)|))[\\x20\\t\\r\\n\\f]*\\)|)",
"i"),Ja:RegExp("^[\\x20\\t\\r\\n\\f]*[>+~]|:(even|odd|eq|gt|lt|nth|first|last)(?:\\([\\x20\\t\\r\\n\\f]*((?:-\\d)?\\d*)[\\x20\\t\\r\\n\\f]*\\)|)(?=[^-]|$)","i")};function Qc(a){var b=R.createElement("div");try{return a(b)}catch(c){return p}finally{}}
var Rc=Qc(function(a){return a.appendChild(R.createComment("")),!a.getElementsByTagName("*").length}),Sc=Qc(function(a){return a.innerHTML="<a href='#'></a>",a.firstChild&&"undefined"!==typeof a.firstChild.getAttribute&&"#"===a.firstChild.getAttribute("href")}),Tc=Qc(function(a){a.innerHTML="<select></select>";a=typeof a.lastChild.getAttribute("multiple");return"boolean"!==a&&"string"!==a}),bc=Qc(function(a){return a.innerHTML="<div class='hidden e'></div><div class='hidden'></div>",!a.getElementsByClassName||
!a.getElementsByClassName("e").length?p:(a.lastChild.className="e",2===a.getElementsByClassName("e").length)}),Uc=Qc(function(a){a.id=V+0;a.innerHTML="<a name='"+V+"'></a><div name='"+V+"'></div>";Z.insertBefore(a,Z.firstChild);var b=R.getElementsByName&&R.getElementsByName(V).length===2+R.getElementsByName(V+0).length;return Cc=!R.getElementById(V),Z.removeChild(a),b});try{ac.call(Z.childNodes,0)[0].nodeType}catch(Vc){ac=function(a){for(var b,c=[];b=this[a];a++)c.push(b);return c}}
P.matches=function(a,b){return P(a,n,n,b)};P.matchesSelector=function(a,b){return 0<P(b,n,n,[a]).length};Dc=P.Yc=function(a){var b,c="",e=0;if(b=a.nodeType)if(1===b||9===b||11===b){if("string"==typeof a.textContent)return a.textContent;for(a=a.firstChild;a;a=a.nextSibling)c+=Dc(a)}else{if(3===b||4===b)return a.nodeValue}else for(;b=a[e];e++)c+=Dc(b);return c};Xb=P.fd=function(a){return(a=a&&(a.ownerDocument||a).documentElement)?"HTML"!==a.nodeName:p};
Zb=P.contains=Z.contains?function(a,b){var c=9===a.nodeType?a.documentElement:a,e=b&&b.parentNode;return a===e||!(!e||!(1===e.nodeType&&c.contains&&c.contains(e)))}:Z.compareDocumentPosition?function(a,b){return b&&!!(a.compareDocumentPosition(b)&16)}:function(a,b){for(;b=b.parentNode;)if(b===a)return d;return p};P.H=function(a,b){var c,e=Xb(a);return e||(b=b.toLowerCase()),(c=W.Ec[b])?c(a):e||Tc?a.getAttribute(b):(c=a.getAttributeNode(b),c?"boolean"==typeof a[b]?a[b]?b:n:c.specified?c.value:n:n)};
W=P.Md={Ic:50,ye:S,match:nc,Ec:Sc?{}:{href:function(a){return a.getAttribute("href",2)},type:function(a){return a.getAttribute("type")}},find:{Sa:Cc?function(a,b,c){if("undefined"!==typeof b.getElementById&&!c)return(a=b.getElementById(a))&&a.parentNode?[a]:[]}:function(a,b,c){if("undefined"!==typeof b.getElementById&&!c)return(b=b.getElementById(a))?b.id===a||"undefined"!==typeof b.getAttributeNode&&b.getAttributeNode("id").value===a?[b]:void 0:[]},Ta:Rc?function(a,b){if("undefined"!==typeof b.getElementsByTagName)return b.getElementsByTagName(a)}:
function(a,b){var c=b.getElementsByTagName(a);if("*"===a){for(var e,f=[],h=0;e=c[h];h++)1===e.nodeType&&f.push(e);return f}return c},vc:Uc&&function(a,b){if("undefined"!==typeof b.getElementsByName)return b.getElementsByName(name)},yb:bc&&function(a,b,c){if("undefined"!==typeof b.getElementsByClassName&&!c)return b.getElementsByClassName(a)}},ea:{">":{dir:"parentNode",Aa:d}," ":{dir:"parentNode"},"+":{dir:"previousSibling",Aa:d},"~":{dir:"previousSibling"}},Ad:{xb:function(a){return a[1]=a[1].replace(yc,
""),a[3]=(a[4]||a[5]||"").replace(yc,""),"~="===a[2]&&(a[3]=" "+a[3]+" "),a.slice(0,4)},Ra:function(a){return a[1]=a[1].toLowerCase(),"nth"===a[1]?(a[2]||P.error(a[0]),a[3]=+(a[3]?a[4]+(a[5]||1):2*("even"===a[2]||"odd"===a[2])),a[4]=+(a[6]+a[7]||"odd"===a[2])):a[2]&&P.error(a[0]),a},zb:function(a){var b,c;if(nc.Ra.test(a[0]))return n;if(a[3])a[2]=a[3];else if(b=a[4])Nc.test(b)&&(c=ic(b,d))&&(c=b.indexOf(")",b.length-c)-b.length)&&(b=b.slice(0,c),a[0]=a[0].slice(0,c)),a[2]=b;return a.slice(0,3)}},
filter:{Sa:Cc?function(a){return a=a.replace(yc,""),function(b){return b.getAttribute("id")===a}}:function(a){return a=a.replace(yc,""),function(b){return(b="undefined"!==typeof b.getAttributeNode&&b.getAttributeNode("id"))&&b.value===a}},Ta:function(a){return"*"===a?function(){return d}:(a=a.replace(yc,"").toLowerCase(),function(b){return b.nodeName&&b.nodeName.toLowerCase()===a})},yb:function(a){var b=Jc[V][a+" "];return b||(b=RegExp("(^|[\\x20\\t\\r\\n\\f])"+a+"([\\x20\\t\\r\\n\\f]|$)"))&&Jc(a,
function(a){return b.test(a.className||"undefined"!==typeof a.getAttribute&&a.getAttribute("class")||"")})},xb:function(a,b,c){return function(e){e=P.H(e,a);return e==n?"!="===b:b?(e+="","="===b?e===c:"!="===b?e!==c:"^="===b?c&&0===e.indexOf(c):"*="===b?c&&-1<e.indexOf(c):"$="===b?c&&e.substr(e.length-c.length)===c:"~="===b?-1<(" "+e+" ").indexOf(c):"|="===b?e===c||e.substr(0,c.length+1)===c+"-":p):d}},Ra:function(a,b,c,e){return"nth"===a?function(a){var b,g;b=a.parentNode;if(1===c&&0===e)return d;
if(b){g=0;for(b=b.firstChild;b&&!(1===b.nodeType&&(g++,a===b));b=b.nextSibling);}return g-=e,g===c||0===g%c&&0<=g/c}:function(b){var c=b;switch(a){case "only":case "first":for(;c=c.previousSibling;)if(1===c.nodeType)return p;if("first"===a)return d;c=b;case "last":for(;c=c.nextSibling;)if(1===c.nodeType)return p;return d}}},zb:function(a,b){var c,e=W.da[a]||W.jc[a.toLowerCase()]||P.error("unsupported pseudo: "+a);return e[V]?e(b):1<e.length?(c=[a,a,"",b],W.jc.hasOwnProperty(a.toLowerCase())?S(function(a,
c){for(var g,j=e(a,b),k=j.length;k--;)g=vc.call(a,j[k]),a[g]=!(c[g]=j[k])}):function(a){return e(a,0,c)}):e}},da:{rd:S(function(a){var b=[],c=[],e=Ac(a.replace(dc,"$1"));return e[V]?S(function(a,b,c,j){j=e(a,n,j,[]);for(var k=a.length;k--;)if(c=j[k])a[k]=!(b[k]=c)}):function(a,h,g){return b[0]=a,e(b,n,g,c),!c.pop()}}),kb:S(function(a){return function(b){return 0<P(a,b).length}}),contains:S(function(a){return function(b){return-1<(b.textContent||b.innerText||Dc(b)).indexOf(a)}}),enabled:function(a){return a.disabled===
p},disabled:function(a){return a.disabled===d},checked:function(a){var b=a.nodeName.toLowerCase();return"input"===b&&!!a.checked||"option"===b&&!!a.selected},selected:function(a){return a.parentNode&&a.parentNode.selectedIndex,a.selected===d},parent:function(a){return!W.da.empty(a)},empty:function(a){var b;for(a=a.firstChild;a;){if("@"<a.nodeName||3===(b=a.nodeType)||4===b)return p;a=a.nextSibling}return d},Qe:function(a){return Oc.test(a.nodeName)},text:function(a){var b,c;return"input"===a.nodeName.toLowerCase()&&
"text"===(b=a.type)&&((c=a.getAttribute("type"))==n||c.toLowerCase()===b)},uf:ec("radio"),re:ec("checkbox"),file:ec("file"),xd:ec("password"),Se:ec("image"),submit:fc("submit"),reset:fc("reset"),button:function(a){var b=a.nodeName.toLowerCase();return"input"===b&&"button"===a.type||"button"===b},input:function(a){return Pc.test(a.nodeName)},focus:function(a){var b=a.ownerDocument;return a===b.activeElement&&(!b.hasFocus||b.hasFocus())&&!(!a.type&&!a.href&&!~a.tabIndex)},Va:function(a){return a===
a.ownerDocument.activeElement},Aa:gc(function(){return[0]}),jd:gc(function(a,b){return[b-1]}),pa:gc(function(a,b,c){return[0>c?c+b:c]}),De:gc(function(a,b){for(var c=0;c<b;c+=2)a.push(c);return a}),ff:gc(function(a,b){for(var c=1;c<b;c+=2)a.push(c);return a}),Ye:gc(function(a,b,c){for(b=0>c?c+b:c;0<=--b;)a.push(b);return a}),Pe:gc(function(a,b,c){for(c=0>c?c+b:c;++c<b;)a.push(c);return a})}};
Ec=Z.compareDocumentPosition?function(a,b){return a===b?(Fc=d,0):(!a.compareDocumentPosition||!b.compareDocumentPosition?a.compareDocumentPosition:a.compareDocumentPosition(b)&4)?-1:1}:function(a,b){if(a===b)return Fc=d,0;if(a.sourceIndex&&b.sourceIndex)return a.sourceIndex-b.sourceIndex;var c,e,f=[],h=[];c=a.parentNode;e=b.parentNode;var g=c;if(c===e)return hc(a,b);if(!c)return-1;if(!e)return 1;for(;g;)f.unshift(g),g=g.parentNode;for(g=e;g;)h.unshift(g),g=g.parentNode;c=f.length;e=h.length;for(g=
0;g<c&&g<e;g++)if(f[g]!==h[g])return hc(f[g],h[g]);return g===c?hc(a,h[g],-1):hc(f[g],b,1)};[0,0].sort(Ec);Gc=!Fc;P.rc=function(a){var b,c=[],e=1,f=0;Fc=Gc;a.sort(Ec);if(Fc){for(;b=a[e];e++)b===a[e-1]&&(f=c.push(e));for(;f--;)a.splice(c[f],1)}return a};P.error=function(a){throw Error("Syntax error, unrecognized expression: "+a);};
Ac=P.compile=function(a,b){var c,e=[],f=[],h=Kc[V][a+" "];if(!h){b||(b=ic(a));for(c=b.length;c--;)h=wc(b[c]),h[V]?e.push(h):f.push(h);var g=0<e.length,j=0<f.length,k=function(a,b,c,h,v){var B,z,y=[],F=0,C="0",H=a&&[],T=v!=n,x=xc,ja=a||j&&W.find.Ta("*",v&&b.parentNode||b),X=qc+=x==n?1:Math.E;for(T&&(xc=b!==R&&b,rc=k.Kb);(v=ja[C])!=n;C++){if(j&&v){for(B=0;z=f[B];B++)if(z(v,b,c)){h.push(v);break}T&&(qc=X,rc=++k.Kb)}g&&((v=!z&&v)&&F--,a&&H.push(v))}F+=C;if(g&&C!==F){for(B=0;z=e[B];B++)z(H,y,b,c);if(a){if(0<
F)for(;C--;)!H[C]&&!y[C]&&(y[C]=Hc.call(h));y=tc(y)}$b.apply(h,y);T&&!a&&0<y.length&&1<F+e.length&&P.rc(h)}return T&&(qc=X,xc=x),H};c=(k.Kb=0,g?S(k):k);h=Kc(a,c)}return h};
if(R.querySelectorAll){var Wc,Xc=cc,Yc=/'|\\/g,Zc=/\=[\x20\t\r\n\f]*([^'"\]]*)[\x20\t\r\n\f]*\]/g,$c=[":focus"],ad=[":active"],bd=Z.matchesSelector||Z.mozMatchesSelector||Z.webkitMatchesSelector||Z.ef||Z.msMatchesSelector;Qc(function(a){a.innerHTML="<select><option selected=''></option></select>";a.querySelectorAll("[selected]").length||$c.push("\\[[\\x20\\t\\r\\n\\f]*(?:checked|disabled|ismap|multiple|readonly|selected|value)");a.querySelectorAll(":checked").length||$c.push(":checked")});Qc(function(a){a.innerHTML=
"<p test=''></p>";a.querySelectorAll("[test^='']").length&&$c.push("[*^$]=[\\x20\\t\\r\\n\\f]*(?:\"\"|'')");a.innerHTML="<input type='hidden'/>";a.querySelectorAll(":enabled").length||$c.push(":enabled",":disabled")});$c=RegExp($c.join("|"));cc=function(a,b,c,e,f){if(!e&&!f&&!$c.test(a)){var h,g,j=d,k=V;g=b;h=9===b.nodeType&&a;if(1===b.nodeType&&"object"!==b.nodeName.toLowerCase()){h=ic(a);(j=b.getAttribute("id"))?k=j.replace(Yc,"\\$&"):b.setAttribute("id",k);k="[id='"+k+"'] ";for(g=h.length;g--;)h[g]=
k+h[g].join("");g=zc.test(a)&&b.parentNode||b;h=h.join(",")}if(h)try{return $b.apply(c,ac.call(g.querySelectorAll(h),0)),c}catch(l){}finally{j||b.removeAttribute("id")}}return Xc(a,b,c,e,f)};bd&&(Qc(function(a){Wc=bd.call(a,"div");try{bd.call(a,"[test!='']:sizzle"),ad.push("!=",Mc)}catch(b){}}),ad=RegExp(ad.join("|")),P.matchesSelector=function(a,b){b=b.replace(Zc,"='$1']");if(!Xb(a)&&!ad.test(b)&&!$c.test(b))try{var c=bd.call(a,b);if(c||Wc||a.document&&11!==a.document.nodeType)return c}catch(e){}return 0<
P(b,n,n,[a]).length})}W.da.df=W.da.pa;W.filters=Bc.prototype=W.da;W.jc=new Bc;P.H=u.H;u.find=P;u.q=P.Md;u.q[":"]=u.q.da;u.unique=P.rc;u.text=P.Yc;u.Ga=P.fd;u.contains=P.contains;var cd=/Until$/,dd=/^(?:parents|prev(?:Until|All))/,la=/^.[^:#\[\.,]*$/,ed=u.q.match.Ja,fd={children:d,ka:d,next:d,Bd:d};
u.b.extend({find:function(a){var b,c,e,f,h,g,j=this;if("string"!=typeof a)return u(a).filter(function(){b=0;for(c=j.length;b<c;b++)if(u.contains(j[b],this))return d});g=this.r("","find",a);b=0;for(c=this.length;b<c;b++)if(e=g.length,u.find(a,this[b],g),0<b)for(f=e;f<g.length;f++)for(h=0;h<e;h++)if(g[h]===g[f]){g.splice(f--,1);break}return g},kb:function(a){var b,c=u(a,this),e=c.length;return this.filter(function(){for(b=0;b<e;b++)if(u.contains(this,c[b]))return d})},rd:function(a){return this.r(ka(this,
a,p),"not",a)},filter:function(a){return this.r(ka(this,a,d),"filter",a)},dd:function(a){return!!a&&("string"==typeof a?ed.test(a)?0<=u(a,this.u).index(this[0]):0<u.filter(a,this).length:0<this.filter(a).length)},ue:function(a,b){for(var c,e=0,f=this.length,h=[],g=ed.test(a)||"string"!=typeof a?u(a,b||this.u):0;e<f;e++)for(c=this[e];c&&c.ownerDocument&&c!==b&&11!==c.nodeType;){if(g?-1<g.index(c):u.find.matchesSelector(c,a)){h.push(c);break}c=c.parentNode}return h=1<h.length?u.unique(h):h,this.r(h,
"closest",a)},index:function(a){return a?"string"==typeof a?u.L(this[0],u(a)):u.L(a.Ia?a[0]:a,this):this[0]&&this[0].parentNode?this.Cd().length:-1},add:function(a,b){var c="string"==typeof a?u(a,b):u.ca(a&&a.nodeType?[a]:a),e=u.A(this.get(),c);return this.r(ha(c[0])||ha(e[0])?e:u.unique(e))},yc:function(a){return this.add(a==n?this.qb:this.qb.filter(a))}});u.b.he=u.b.yc;
u.a({parent:function(a){return(a=a.parentNode)&&11!==a.nodeType?a:n},mf:function(a){return u.dir(a,"parentNode")},nf:function(a,b,c){return u.dir(a,"parentNode",c)},next:function(a){return ia(a,"nextSibling")},Bd:function(a){return ia(a,"previousSibling")},$e:function(a){return u.dir(a,"nextSibling")},Cd:function(a){return u.dir(a,"previousSibling")},af:function(a,b,c){return u.dir(a,"nextSibling",c)},sf:function(a,b,c){return u.dir(a,"previousSibling",c)},Cf:function(a){return u.lc((a.parentNode||
{}).firstChild,a)},children:function(a){return u.lc(a.firstChild)},ka:function(a){return u.nodeName(a,"iframe")?a.contentDocument||a.contentWindow.document:u.A([],a.childNodes)}},function(a,b){u.b[a]=function(c,e){var f=u.map(this,b,c);return cd.test(a)||(e=c),e&&"string"==typeof e&&(f=u.filter(e,f)),f=1<this.length&&!fd[a]?u.unique(f):f,1<this.length&&dd.test(a)&&(f=f.reverse()),this.r(f,a,E.call(arguments).join(","))}});
u.extend({filter:function(a,b,c){return c&&(a=":not("+a+")"),1===b.length?u.find.matchesSelector(b[0],a)?[b[0]]:[]:u.find.matches(a,b)},dir:function(a,b,c){var e=[];for(a=a[b];a&&9!==a.nodeType&&(c===s||1!==a.nodeType||!u(a).dd(c));)1===a.nodeType&&e.push(a),a=a[b];return e},lc:function(a,b){for(var c=[];a;a=a.nextSibling)1===a.nodeType&&a!==b&&c.push(a);return c}});
var na="abbr|article|aside|audio|bdi|canvas|data|datalist|details|figcaption|figure|footer|header|hgroup|mark|meter|nav|output|progress|section|summary|time|video",gd=/ jQuery\d+="(?:null|\d+)"/g,hd=/^\s+/,id=/<(?!area|br|col|embed|hr|img|input|link|meta|param)(([\w:]+)[^>]*)\/>/gi,jd=/<([\w:]+)/,kd=/<tbody/i,ld=/<|&#?\w+;/,md=/<(?:script|style|link)/i,nd=/<(?:script|object|embed|option|style)/i,od=RegExp("<(?:"+na+")[\\s/>]","i"),qa=/^(?:checkbox|radio)$/,pd=/checked\s*(?:[^=]|=\s*.checked.)/i,qd=
/\/(java|ecma)script/i,rd=/^\s*<!(?:\[CDATA\[|\-\-)|[\]\-]{2}>\s*$/g,$={ac:[1,"<select multiple='multiple'>","</select>"],Ue:[1,"<fieldset>","</fieldset>"],Rd:[1,"<table>","</table>"],Nf:[2,"<table><tbody>","</tbody></table>"],Qd:[3,"<table><tbody><tr>","</tr></tbody></table>"],ve:[2,"<table><tbody></tbody><colgroup>","</colgroup></table>"],ke:[1,"<map>","</map>"],C:[0,"",""]},sd=ma(A),td=sd.appendChild(A.createElement("div"));$.jf=$.ac;$.qc=$.Lf=$.we=$.caption=$.Rd;$.Mf=$.Qd;
u.c.Qb||($.C=[1,"X<div>","</div>"]);
u.b.extend({text:function(a){return u.D(this,function(a){return a===s?u.text(this):this.empty().append((this[0]&&this[0].ownerDocument||A).createTextNode(a))},n,a,arguments.length)},wb:function(a){if(u.d(a))return this.a(function(b){u(this).wb(a.call(this,b))});if(this[0]){var b=u(a,this[0].ownerDocument).pa(0).Y(d);this[0].parentNode&&b.insertBefore(this[0]);b.map(function(){for(var a=this;a.firstChild&&1===a.firstChild.nodeType;)a=a.firstChild;return a}).append(this)}return this},ae:function(a){return u.d(a)?
this.a(function(b){u(this).ae(a.call(this,b))}):this.a(function(){var b=u(this),c=b.ka();c.length?c.wb(a):b.append(a)})},Xf:function(a){var b=u.d(a);return this.a(function(c){u(this).wb(b?a.call(this,c):a)})},Sf:function(){return this.parent().a(function(){u.nodeName(this,"body")||u(this).hc(this.childNodes)}).end()},append:function(){return this.aa(arguments,d,function(a){(1===this.nodeType||11===this.nodeType)&&this.appendChild(a)})},qf:function(){return this.aa(arguments,d,function(a){(1===this.nodeType||
11===this.nodeType)&&this.insertBefore(a,this.firstChild)})},Fc:function(){if(!ha(this[0]))return this.aa(arguments,p,function(a){this.parentNode.insertBefore(a,this)});if(arguments.length){var a=u.$a(arguments);return this.r(u.A(a,this),"before",this.i)}},ge:function(){if(!ha(this[0]))return this.aa(arguments,p,function(a){this.parentNode.insertBefore(a,this.nextSibling)});if(arguments.length){var a=u.$a(arguments);return this.r(u.A(this,a),"after",this.i)}},remove:function(a,b){for(var c,e=0;(c=
this[e])!=n;e++)if(!a||u.filter(a,[c]).length)!b&&1===c.nodeType&&(u.ja(c.getElementsByTagName("*")),u.ja([c])),c.parentNode&&c.parentNode.removeChild(c);return this},empty:function(){for(var a,b=0;(a=this[b])!=n;b++)for(1===a.nodeType&&u.ja(a.getElementsByTagName("*"));a.firstChild;)a.removeChild(a.firstChild);return this},Y:function(a,b){return a=a==n?p:a,b=b==n?a:b,this.map(function(){return u.Y(this,a,b)})},sa:function(a){return u.D(this,function(a){var c=this[0]||{},e=0,f=this.length;if(a===
s)return 1===c.nodeType?c.innerHTML.replace(gd,""):s;if("string"==typeof a&&!md.test(a)&&(u.c.Qb||!od.test(a))&&(u.c.Wb||!hd.test(a))&&!$[(jd.exec(a)||["",""])[1].toLowerCase()]){a=a.replace(id,"<$1></$2>");try{for(;e<f;e++)c=this[e]||{},1===c.nodeType&&(u.ja(c.getElementsByTagName("*")),c.innerHTML=a);c=0}catch(h){}}c&&this.empty().append(a)},n,a,arguments.length)},hc:function(a){return ha(this[0])?this.length?this.r(u(u.d(a)?a():a),"replaceWith",a):this:u.d(a)?this.a(function(b){var c=u(this),e=
c.sa();c.hc(a.call(this,b,e))}):("string"!=typeof a&&(a=u(a).detach()),this.a(function(){var b=this.nextSibling,c=this.parentNode;u(this).remove();b?u(b).Fc(a):u(c).append(a)}))},detach:function(a){return this.remove(a,d)},aa:function(a,b,c){a=[].concat.apply([],a);var e,f,h,g=0,j=a[0],k=[],l=this.length;if(!u.c.Hb&&1<l&&"string"==typeof j&&pd.test(j))return this.a(function(){u(this).aa(a,b,c)});if(u.d(j))return this.a(function(e){var f=u(this);a[0]=j.call(this,e,b?f.sa():s);f.aa(a,b,c)});if(this[0]){e=
u.Fb(a,this,k);h=e.jb;f=h.firstChild;1===h.childNodes.length&&(h=f);if(f){b=b&&u.nodeName(f,"tr");for(e=e.Gb||l-1;g<l;g++)c.call(b&&u.nodeName(this[g],"table")?this[g].getElementsByTagName("tbody")[0]||this[g].appendChild(this[g].ownerDocument.createElement("tbody")):this[g],g===e?h:u.Y(h,d,d))}h=f=n;k.length&&u.a(k,function(a,b){b.src?u.X?u.X({url:b.src,type:"GET",dataType:"script",async:p,global:p,"throws":d}):u.error("no ajax"):u.Nb((b.text||b.textContent||b.innerHTML||"").replace(rd,""));b.parentNode&&
b.parentNode.removeChild(b)})}return this}});u.Fb=function(a,b,c){var e,f,h,g=a[0];return b=b||A,b=!b.nodeType&&b[0]||b,b=b.ownerDocument||b,1===a.length&&"string"==typeof g&&512>g.length&&b===A&&"<"===g.charAt(0)&&!nd.test(g)&&(u.c.Hb||!pd.test(g))&&(u.c.mb||!od.test(g))&&(f=d,e=u.Mb[g],h=e!==s),e||(e=b.createDocumentFragment(),u.$a(a,b,e,c),f&&(u.Mb[g]=h&&e)),{jb:e,Gb:f}};u.Mb={};
u.a({Dc:"append",rf:"prepend",insertBefore:"before",Te:"after",xf:"replaceWith"},function(a,b){u.b[a]=function(c){var e,f=0,h=[];c=u(c);var g=c.length;e=1===this.length&&this[0].parentNode;if((e==n||e&&11===e.nodeType&&1===e.childNodes.length)&&1===g)return c[b](this[0]),this;for(;f<g;f++)e=(0<f?this.Y(d):this).get(),u(c[f])[b](e),h=h.concat(e);return this.r(h,a,c.i)}});
u.extend({Y:function(a,b,c){var e,f,h,g;u.c.mb||u.Ga(a)||!od.test("<"+a.nodeName+">")?g=a.cloneNode(d):(td.innerHTML=a.outerHTML,td.removeChild(g=td.firstChild));if((!u.c.Yb||!u.c.pd)&&(1===a.nodeType||11===a.nodeType)&&!u.Ga(a)){pa(a,g);e=ra(a);f=ra(g);for(h=0;e[h];++h)f[h]&&pa(e[h],f[h])}if(b&&(oa(a,g),c)){e=ra(a);f=ra(g);for(h=0;e[h];++h)oa(e[h],f[h])}return g},$a:function(a,b,c,e){var f,h,g,j,k,l,q,m=b===A&&sd,t=[];if(!b||"undefined"==typeof b.createDocumentFragment)b=A;for(f=0;(g=a[f])!=n;f++)if("number"==
typeof g&&(g+=""),g){if("string"==typeof g)if(ld.test(g)){m=m||ma(b);l=b.createElement("div");m.appendChild(l);g=g.replace(id,"<$1></$2>");h=(jd.exec(g)||["",""])[1].toLowerCase();j=$[h]||$.C;k=j[0];for(l.innerHTML=j[1]+g+j[2];k--;)l=l.lastChild;if(!u.c.qc){k=kd.test(g);j="table"===h&&!k?l.firstChild&&l.firstChild.childNodes:"<table>"===j[1]&&!k?l.childNodes:[];for(h=j.length-1;0<=h;--h)u.nodeName(j[h],"tbody")&&!j[h].childNodes.length&&j[h].parentNode.removeChild(j[h])}!u.c.Wb&&hd.test(g)&&l.insertBefore(b.createTextNode(hd.exec(g)[0]),
l.firstChild);g=l.childNodes;l.parentNode.removeChild(l)}else g=b.createTextNode(g);g.nodeType?t.push(g):u.A(t,g)}l&&(g=l=m=n);if(!u.c.Cc)for(f=0;(g=t[f])!=n;f++)u.nodeName(g,"input")?sa(g):"undefined"!=typeof g.getElementsByTagName&&u.T(g.getElementsByTagName("input"),sa);if(c){a=function(a){if(!a.type||qd.test(a.type))return e?e.push(a.parentNode?a.parentNode.removeChild(a):a):c.appendChild(a)};for(f=0;(g=t[f])!=n;f++)if(!u.nodeName(g,"script")||!a(g))c.appendChild(g),"undefined"!=typeof g.getElementsByTagName&&
(q=u.T(u.A([],g.getElementsByTagName("script")),a),t.splice.apply(t,[f+1,0].concat(q)),f+=q.length)}return t},ja:function(a,b){for(var c,e,f,h,g=0,j=u.expando,k=u.I,l=u.c.eb,q=u.event.t;(f=a[g])!=n;g++)if(b||u.ia(f))if(c=(e=f[j])&&k[e]){if(c.J)for(h in c.J)q[h]?u.event.remove(f,h):u.gc(f,h,c.handle);k[e]&&(delete k[e],l?delete f[j]:f.removeAttribute?f.removeAttribute(j):f[j]=n,u.Jb.push(e))}}});var ud,vd;
u.Yd=function(){var a=$a.userAgent,a=a.toLowerCase(),a=/(chrome)[ \/]([\w.]+)/.exec(a)||/(webkit)[ \/]([\w.]+)/.exec(a)||/(opera)(?:.*version|)[ \/]([\w.]+)/.exec(a)||/(msie) ([\w.]+)/.exec(a)||0>a.indexOf("compatible")&&/(mozilla)(?:.*? rv:([\w.]+)|)/.exec(a)||[];return{Za:a[1]||"",version:a[2]||"0"}};ud=u.Yd();vd={};ud.Za&&(vd[ud.Za]=d,vd.version=ud.version);vd.se?vd.$d=d:vd.$d&&(vd.Af=d);u.Za=vd;
u.sub=function(){function a(b,e){return new a.b.z(b,e)}u.extend(d,a,this);a.If=this;a.b=a.prototype=this();a.b.constructor=a;a.sub=this.sub;a.b.z=function(c,e){return e&&e instanceof u&&!(e instanceof a)&&(e=a(e)),u.b.z.call(this,c,e,b)};a.b.z.prototype=a.b;var b=a(A);return a};
var w,Fa,Ga,wd=/alpha\([^)]*\)/i,xd=/opacity=([^)]*)/,yd=/^(top|right|bottom|left)$/,zd=/^(none|table(?!-c[ea]).+)/,Ad=/^margin/,za=RegExp("^("+hb+")(.*)$","i"),Da=RegExp("^("+hb+")(?!px)[a-z%]+$","i"),Bd=RegExp("^([-+])=("+hb+")","i"),Ea={ce:"block"},Cd={position:"absolute",visibility:"hidden",display:"block"},Dd={letterSpacing:0,fontWeight:400},Ba=["Top","Right","Bottom","Left"],ua=["Webkit","O","Moz","ms"],Ed=u.b.toggle;
u.b.extend({g:function(a,b){return u.D(this,function(a,b,f){return f!==s?u.style(a,b,f):u.g(a,b)},a,b,1<arguments.length)},show:function(){return wa(this,d)},Pb:function(){return wa(this)},toggle:function(a,b){var c="boolean"==typeof a;return u.d(a)&&u.d(b)?Ed.apply(this,arguments):this.a(function(){(c?a:va(this))?u(this).show():u(this).Pb()})}});
u.extend({p:{opacity:{get:function(a,b){if(b){var c=w(a,"opacity");return""===c?"1":c}}}},ab:{Je:d,fontWeight:d,lineHeight:d,opacity:d,orphans:d,widows:d,zIndex:d,zoom:d},ma:{"float":u.c.cssFloat?"cssFloat":"styleFloat"},style:function(a,b,c,e){if(a&&!(3===a.nodeType||8===a.nodeType||!a.style)){var f,h,g,j=u.S(b),k=a.style;b=u.ma[j]||(u.ma[j]=ta(k,j));g=u.p[b]||u.p[j];if(c===s)return g&&"get"in g&&(f=g.get(a,p,e))!==s?f:k[b];h=typeof c;"string"===h&&(f=Bd.exec(c))&&(c=(f[1]+1)*f[2]+parseFloat(u.g(a,
b)),h="number");if(!(c==n||"number"===h&&isNaN(c)))if("number"===h&&!u.ab[j]&&(c+="px"),!g||!("set"in g)||(c=g.set(a,c,e))!==s)try{k[b]=c}catch(l){}}},g:function(a,b,c,e){var f,h,g,j=u.S(b);return b=u.ma[j]||(u.ma[j]=ta(a.style,j)),g=u.p[b]||u.p[j],g&&"get"in g&&(f=g.get(a,d,e)),f===s&&(f=w(a,b)),"normal"===f&&b in Dd&&(f=Dd[b]),c||e!==s?(h=parseFloat(f),c||u.Tb(h)?h||0:f):f},pc:function(a,b,c){var e,f={};for(e in b)f[e]=a.style[e],a.style[e]=b[e];c=c.call(a);for(e in b)a.style[e]=f[e];return c}});
r.getComputedStyle?w=function(a,b){var c,e,f,h,g=r.getComputedStyle(a,n),j=a.style;return g&&(c=g.getPropertyValue(b)||g[b],""===c&&!u.contains(a.ownerDocument,a)&&(c=u.style(a,b)),Da.test(c)&&Ad.test(b)&&(e=j.width,f=j.minWidth,h=j.maxWidth,j.minWidth=j.maxWidth=j.width=c,c=g.width,j.width=e,j.minWidth=f,j.maxWidth=h)),c}:A.documentElement.currentStyle&&(w=function(a,b){var c,e,f=a.currentStyle&&a.currentStyle[b],h=a.style;return f==n&&h&&h[b]&&(f=h[b]),Da.test(f)&&!yd.test(b)&&(c=h.left,e=a.runtimeStyle&&
a.runtimeStyle.left,e&&(a.runtimeStyle.left=a.currentStyle.left),h.left="fontSize"===b?"1em":f,f=h.pixelLeft+"px",h.left=c,e&&(a.runtimeStyle.left=e)),""===f?"auto":f});u.a(["height","width"],function(a,b){u.p[b]={get:function(a,e,f){if(e)return 0===a.offsetWidth&&zd.test(w(a,"display"))?u.pc(a,Cd,function(){return Ca(a,b,f)}):Ca(a,b,f)},set:function(a,e,f){return ya(0,e,f?Aa(a,b,f,u.c.boxSizing&&"border-box"===u.g(a,"boxSizing")):0)}}});
u.c.opacity||(u.p.opacity={get:function(a,b){return xd.test((b&&a.currentStyle?a.currentStyle.filter:a.style.filter)||"")?0.01*parseFloat(RegExp.$1)+"":b?"1":""},set:function(a,b){var c=a.style,e=a.currentStyle,f=u.Tb(b)?"alpha(opacity="+100*b+")":"",h=e&&e.filter||c.filter||"";c.zoom=1;if(1<=b&&(""===u.trim(h.replace(wd,""))&&c.removeAttribute)&&(c.removeAttribute("filter"),e&&!e.filter))return;c.filter=wd.test(h)?h.replace(wd,f):h+" "+f}});
u(function(){u.c.fc||(u.p.marginRight={get:function(a,b){return u.pc(a,{display:"inline-block"},function(){if(b)return w(a,"marginRight")})}});!u.c.dc&&u.b.position&&u.a(["top","left"],function(a,b){u.p[b]={get:function(a,e){if(e){var f=w(a,b);return Da.test(f)?u(a).position()[b]+"px":f}}}})});u.q&&u.q.filters&&(u.q.filters.hidden=function(a){return 0===a.offsetWidth&&0===a.offsetHeight||!u.c.Hd&&"none"===(a.style&&a.style.display||w(a,"display"))},u.q.filters.visible=function(a){return!u.q.filters.hidden(a)});
u.a({margin:"",padding:"",border:"Width"},function(a,b){u.p[a+b]={expand:function(c){var e="string"==typeof c?c.split(" "):[c],f={};for(c=0;4>c;c++)f[a+Ba[c]+b]=e[c]||e[c-2]||e[0];return f}};Ad.test(a)||(u.p[a+b].set=ya)});var Fd=/%20/g,Ia=/\[\]$/,Gd=/\r?\n/g,Hd=/^(?:color|date|datetime|datetime-local|email|hidden|month|number|password|range|search|tel|text|time|url|week)$/i,Id=/^(?:select|textarea)/i;
u.b.extend({Bf:function(){return u.bc(this.Nd())},Nd:function(){return this.map(function(){return this.elements?u.ca(this.elements):this}).filter(function(){return this.name&&!this.disabled&&(this.checked||Id.test(this.nodeName)||Hd.test(this.type))}).map(function(a,b){var c=u(this).ya();return c==n?n:u.isArray(c)?u.map(c,function(a){return{name:b.name,value:a.replace(Gd,"\r\n")}}):{name:b.name,value:c.replace(Gd,"\r\n")}}).get()}});
u.bc=function(a,b){function c(a,b){b=u.d(b)?b():b==n?"":b;f[f.length]=encodeURIComponent(a)+"="+encodeURIComponent(b)}var e,f=[];b===s&&(b=u.P&&u.P.Xd);if(u.isArray(a)||a.Ia&&!u.Ea(a))u.a(a,function(){c(this.name,this.value)});else for(e in a)Ha(e,a[e],b,c);return f.join("&").replace(Fd,"+")};
var Jd,Kd,Ld=/#.*$/,Md=/^(.*?):[ \t]*([^\r\n]*)\r?$/mg,Nd=/^(?:GET|HEAD)$/,Od=/^\/\//,Pd=/\?/,Qd=/<script\b[^<]*(?:(?!<\/script>)<[^<]*)*<\/script>/gi,Rd=/([?&])_=[^&]*/,Sd=/^([\w\+\.\-]+:)(?:\/\/([^\/?#:]*)(?::(\d+)|)|)/,Td=u.b.load,Ma={},Ud={},Vd=["*/"]+["*"];try{Kd=Za.href}catch(Wd){Kd=A.createElement("a"),Kd.href="",Kd=Kd.href}Jd=Sd.exec(Kd.toLowerCase())||[];
u.b.load=function(a,b,c){if("string"!=typeof a&&Td)return Td.apply(this,arguments);if(!this.length)return this;var e,f,h,g=this,j=a.indexOf(" ");return 0<=j&&(e=a.slice(j,a.length),a=a.slice(0,j)),u.d(b)?(c=b,b=s):b&&"object"==typeof b&&(f="POST"),u.X({url:a,type:f,dataType:"html",data:b,complete:function(a,b){c&&g.a(c,h||[a.responseText,b,a])}}).w(function(a){h=arguments;g.sa(e?u("<div>").append(a.replace(Qd,"")).find(e):a)}),this};
u.a("ajaxStart ajaxStop ajaxComplete ajaxError ajaxSuccess ajaxSend".split(" "),function(a,b){u.b[b]=function(a){return this.V(b,a)}});u.a(["get","post"],function(a,b){u[b]=function(a,e,f,h){return u.d(e)&&(h=h||f,f=e,e=s),u.X({type:b,url:a,data:e,oc:f,dataType:h})}});
u.extend({Oe:function(a,b){return u.get(a,s,b,"script")},Ne:function(a,b,c){return u.get(a,b,c,"json")},Wa:function(a,b){return b?Na(a,u.P):(b=a,a=u.P),Na(a,b),a},P:{url:Kd,Sb:/^(?:about|app|app\-storage|.+\-extension|file|res|widget):$/.test(Jd[1]),global:d,type:"GET",contentType:"application/x-www-form-urlencoded; charset=UTF-8",Dd:d,async:d,za:{xml:"application/xml, text/xml",sa:"text/html",text:"text/plain",gd:"application/json, text/javascript","*":Vd},ka:{xml:/xml/,sa:/html/,gd:/json/},Jd:{xml:"responseXML",
text:"responseText"},la:{"* text":r.ee,"text html":d,"text json":u.cc,"text xml":u.wd},Uc:{u:d,url:d}},Cb:Ja(Ma),Db:Ja(Ud),X:function(a,b){function c(a,b,c,h){var k,q,C,F,U,J=b;if(2!==H){H=2;j&&clearTimeout(j);g=s;f=h||"";x.readyState=0<a?4:0;if(c){F=m;h=x;var Q,M,da,T,X=F.ka,Y=F.v,ja=F.Jd;for(M in ja)M in c&&(h[ja[M]]=c[M]);for(;"*"===Y[0];)Y.shift(),Q===s&&(Q=F.pb||h.getResponseHeader("content-type"));if(Q)for(M in X)if(X[M]&&X[M].test(Q)){Y.unshift(M);break}if(Y[0]in c)da=Y[0];else{for(M in c){if(!Y[0]||
F.la[M+" "+Y[0]]){da=M;break}T||(T=M)}da=da||T}F=da?(da!==Y[0]&&Y.unshift(da),c[da]):void 0}if(200<=a&&300>a||304===a)if(m.bd&&(U=x.getResponseHeader("Last-Modified"),U&&(u.lastModified[e]=U),U=x.getResponseHeader("Etag"),U&&(u.gb[e]=U)),304===a)J="notmodified",k=d;else{var K;a:{c=m;k=F;var Xa;U=c.v.slice();J=U[0];Q={};M=0;c.Qc&&(k=c.Qc(k,c.dataType));if(U[1])for(K in c.la)Q[K.toLowerCase()]=c.la[K];for(;q=U[++M];)if("*"!==q){if("*"!==J&&J!==q){K=Q[J+" "+q]||Q["* "+q];if(!K)for(Xa in Q)if(C=Xa.split(" "),
C[1]===q&&(K=Q[J+" "+C[0]]||Q["* "+C[0]])){K===d?K=Q[Xa]:Q[Xa]!==d&&(q=C[0],U.splice(M--,0,q));break}if(K!==d)if(K&&c["throws"])k=K(k);else try{k=K(k)}catch(ae){K={state:"parsererror",error:K?ae:"No conversion from "+J+" to "+q};break a}}J=q}K={state:"success",data:k}}k=K;J=k.state;q=k.data;C=k.error;k=!C}else if(C=J,!J||a)J="error",0>a&&(a=0);x.status=a;x.statusText=(b||J)+"";k?B.ga(t,[q,J,x]):B.Gd(t,[x,J,C]);x.nc(y);y=s;l&&v.n("ajax"+(k?"Success":"Error"),[x,m,k?q:C]);z.hb(t,[x,J]);l&&(v.n("ajaxComplete",
[x,m]),--u.Va||u.event.n("ajaxStop"))}}"object"==typeof a&&(b=a,a=s);b=b||{};var e,f,h,g,j,k,l,q,m=u.Wa({},b),t=m.u||m,v=t!==m&&(t.nodeType||t instanceof u)?u(t):u.event,B=u.W(),z=u.ha("once memory"),y=m.nc||{},F={},C={},H=0,T="canceled",x={readyState:0,setRequestHeader:function(a,b){if(!H){var c=a.toLowerCase();a=C[c]=C[c]||a;F[a]=b}return this},getAllResponseHeaders:function(){return 2===H?f:n},getResponseHeader:function(a){var b;if(2===H){if(!h)for(h={};b=Md.exec(f);)h[b[1].toLowerCase()]=b[2];
b=h[a.toLowerCase()]}return b===s?n:b},overrideMimeType:function(a){return H||(m.pb=a),this},abort:function(a){return a=a||T,g&&g.abort(a),c(0,a),this}};B.m(x);x.oc=x.w;x.error=x.qa;x.complete=z.add;x.nc=function(a){if(a){var b;if(2>H)for(b in a)y[b]=[y[b],a[b]];else b=a[x.status],x.Q(b)}return this};m.url=((a||m.url)+"").replace(Ld,"").replace(Od,Jd[1]+"//");m.v=u.trim(m.dataType||"*").toLowerCase().split(Ka);m.Z==n&&(k=Sd.exec(m.url.toLowerCase()),m.Z=!(!k||k[1]===Jd[1]&&k[2]===Jd[2]&&(k[3]||("http:"===
k[1]?80:443))==(Jd[3]||("http:"===Jd[1]?80:443))));m.data&&m.Dd&&"string"!=typeof m.data&&(m.data=u.bc(m.data,m.Xd));La(Ma,m,b,x);if(2===H)return x;l=m.global;m.type=m.type.toUpperCase();m.lb=!Nd.test(m.type);l&&0===u.Va++&&u.event.n("ajaxStart");if(!m.lb&&(m.data&&(m.url+=(Pd.test(m.url)?"&":"?")+m.data,delete m.data),e=m.url,m.I===p)){k=u.now();var ja=m.url.replace(Rd,"$1_="+k);m.url=ja+(ja===m.url?(Pd.test(m.url)?"&":"?")+"_="+k:"")}(m.data&&m.lb&&m.contentType!==p||b.contentType)&&x.setRequestHeader("Content-Type",
m.contentType);m.bd&&(e=e||m.url,u.lastModified[e]&&x.setRequestHeader("If-Modified-Since",u.lastModified[e]),u.gb[e]&&x.setRequestHeader("If-None-Match",u.gb[e]));x.setRequestHeader("Accept",m.v[0]&&m.za[m.v[0]]?m.za[m.v[0]]+("*"!==m.v[0]?", "+Vd+"; q=0.01":""):m.za["*"]);for(q in m.headers)x.setRequestHeader(q,m.headers[q]);if(!m.Gc||m.Gc.call(t,x,m)!==p&&2!==H){T="abort";for(q in{oc:1,error:1,complete:1})x[q](m[q]);if(g=La(Ud,m,b,x)){x.readyState=1;l&&v.n("ajaxSend",[x,m]);m.async&&0<m.timeout&&
(j=setTimeout(function(){x.abort("timeout")},m.timeout));try{H=1,g.send(F,c)}catch(X){if(!(2>H))throw X;c(-1,X)}}else c(-1,"No Transport");return x}return x.abort()},Va:0,lastModified:{},gb:{}});var Xd=[],Yd=/\?/,Zd=/(=)\?(?=&|$)|\?\?/,$d=u.now();u.Wa({Vb:"callback",ba:function(){var a=Xd.pop()||u.expando+"_"+$d++;return this[a]=d,a}});
u.Cb("json jsonp",function(a,b,c){var e,f,h,g=a.data,j=a.url,k=a.Vb!==p,l=k&&Zd.test(j),q=k&&!l&&"string"==typeof g&&!(a.contentType||"").indexOf("application/x-www-form-urlencoded")&&Zd.test(g);if("jsonp"===a.v[0]||l||q)return e=a.ba=u.d(a.ba)?a.ba():a.ba,f=r[e],l?a.url=j.replace(Zd,"$1"+e):q?a.data=g.replace(Zd,"$1"+e):k&&(a.url+=(Yd.test(j)?"&":"?")+a.Vb+"="+e),a.la["script json"]=function(){return h||u.error(e+" was not called"),h[0]},a.v[0]="json",r[e]=function(){h=arguments},c.Q(function(){r[e]=
f;a[e]&&(a.ba=b.ba,Xd.push(e));h&&u.d(f)&&f(h[0]);h=f=s}),"script"});u.Wa({za:{Kd:"text/javascript, application/javascript, application/ecmascript, application/x-ecmascript"},ka:{Kd:/javascript|ecmascript/},la:{"text script":function(a){return u.Nb(a),a}}});u.Cb("script",function(a){a.I===s&&(a.I=p);a.Z&&(a.type="GET",a.global=p)});
u.Db("script",function(a){if(a.Z){var b,c=A.head||A.getElementsByTagName("head")[0]||A.documentElement;return{send:function(e,f){b=A.createElement("script");b.async="async";a.Ld&&(b.charset=a.Ld);b.src=a.url;b.onload=b.onreadystatechange=function(a,e){if(e||!b.readyState||/loaded|complete/.test(b.readyState))b.onload=b.onreadystatechange=n,c&&b.parentNode&&c.removeChild(b),b=s,e||f(200,"success")};c.insertBefore(b,c.firstChild)},abort:function(){b&&b.onload(0,1)}}}});
var be,ce=r.ActiveXObject?function(){for(var a in be)be[a](0,1)}:p,de=0;u.P.tc=r.ActiveXObject?function(){var a;if(!(a=!this.Sb&&Oa()))a:{try{a=new r.ActiveXObject("Microsoft.XMLHTTP");break a}catch(b){}a=void 0}return a}:Oa;var ee=u.P.tc();u.extend(u.c,{X:!!ee,Oc:!!ee&&"withCredentials"in ee});
u.c.X&&u.Db(function(a){if(!a.Z||u.c.Oc){var b;return{send:function(c,e){var f,h,g=a.tc();a.Zd?g.open(a.type,a.url,a.async,a.Zd,a.xd):g.open(a.type,a.url,a.async);if(a.uc)for(h in a.uc)g[h]=a.uc[h];a.pb&&g.overrideMimeType&&g.overrideMimeType(a.pb);!a.Z&&!c["X-Requested-With"]&&(c["X-Requested-With"]="XMLHttpRequest");try{for(h in c)g.setRequestHeader(h,c[h])}catch(j){}g.send(a.lb&&a.data||n);b=function(c,h){var j,m,t,v,B;try{if(b&&(h||4===g.readyState))if(b=s,f&&(g.onreadystatechange=u.Zb,ce&&delete be[f]),
h)4!==g.readyState&&g.abort();else{j=g.status;t=g.getAllResponseHeaders();v={};(B=g.responseXML)&&B.documentElement&&(v.xml=B);try{v.text=g.responseText}catch(z){}try{m=g.statusText}catch(y){m=""}!j&&a.Sb&&!a.Z?j=v.text?200:404:1223===j&&(j=204)}}catch(F){h||e(-1,F)}v&&e(j,m,v,t)};a.async?4===g.readyState?setTimeout(b,0):(f=++de,ce&&(be||(be={},u(r).Rf(ce)),be[f]=b),g.onreadystatechange=b):b()},abort:function(){b&&b(0,1)}}}});
var Qa,fe,ge=/^(?:toggle|show|hide)$/,he=RegExp("^(?:([-+])=|)("+hb+")([a-z%]*)$","i"),ie=/queueHooks$/,Sa=[function(a,b,c){var e,f,h,g,j,k,l=this,q=a.style,m={},t=[],v=a.nodeType&&va(a);c.j||(j=u.Ua(a,"fx"),j.Pa==n&&(j.Pa=0,k=j.empty.ra,j.empty.ra=function(){j.Pa||k()}),j.Pa++,l.Q(function(){l.Q(function(){j.Pa--;u.j(a,"fx").length||j.empty.ra()})}));1===a.nodeType&&("height"in b||"width"in b)&&(c.overflow=[q.overflow,q.overflowX,q.overflowY],"inline"===u.g(a,"display")&&"none"===u.g(a,"float")&&
(!u.c.Rb||"inline"===xa(a.nodeName)?q.display="inline-block":q.zoom=1));c.overflow&&(q.overflow="hidden",u.c.kc||l.w(function(){q.overflow=c.overflow[0];q.overflowX=c.overflow[1];q.overflowY=c.overflow[2]}));for(e in b)h=b[e],ge.exec(h)&&(delete b[e],f=f||"toggle"===h,h!==(v?"hide":"show")&&t.push(e));if(b=t.length){h=u.e(a,"fxshow")||u.e(a,"fxshow",{});"hidden"in h&&(v=h.hidden);f&&(h.hidden=!v);v?u(a).show():l.w(function(){u(a).Pb()});l.w(function(){var b;u.fa(a,"fxshow",d);for(b in m)u.style(a,
b,m[b])});for(e=0;e<b;e++)f=t[e],g=l.Ib(f,v?h[f]:0),m[f]=h[f]||u.style(a,f),f in h||(h[f]=g.start,v&&(g.end=g.start,g.start="width"===f||"height"===f?1:0))}}],Ta={"*":[function(a,b){var c,e,f=this.Ib(a,b),h=he.exec(b),g=f.bb(),j=+g||0,k=1,l=20;if(h){c=+h[2];e=h[3]||(u.ab[a]?"":"px");if("px"!==e&&j){j=u.g(f.f,a,d)||c||1;do k=k||".5",j/=k,u.style(f.f,a,j+e);while(k!==(k=f.bb()/g)&&1!==k&&--l)}f.sc=e;f.start=j;f.end=h[1]?j+(h[1]+1)*c:c}return f}]};
u.be=u.extend(Ra,{Of:function(a,b){u.d(a)?(b=a,a=["*"]):a=a.split(" ");for(var c,e=0,f=a.length;e<f;e++)c=a[e],Ta[c]=Ta[c]||[],Ta[c].unshift(b)},pf:function(a,b){b?Sa.unshift(a):Sa.push(a)}});u.xc=D;
D.prototype={constructor:D,z:function(a,b,c,e,f,h){this.f=a;this.l=c;this.oa=f||"swing";this.options=b;this.start=this.now=this.bb();this.end=e;this.sc=h||(u.ab[c]?"":"px")},bb:function(){var a=D.B[this.l];return a&&a.get?a.get(this):D.B.C.get(this)},ic:function(a){var b,c=D.B[this.l];return this.options.duration?this.yd=b=u.oa[this.oa](a,this.options.duration*a,0,1,this.options.duration):this.yd=b=a,this.now=(this.end-this.start)*b+this.start,this.options.step&&this.options.step.call(this.f,this.now,
this),c&&c.set?c.set(this):D.B.C.set(this),this}};D.prototype.z.prototype=D.prototype;D.B={C:{get:function(a){var b;return a.f[a.l]==n||a.f.style&&a.f.style[a.l]!=n?(b=u.g(a.f,a.l,p,""),!b||"auto"===b?0:b):a.f[a.l]},set:function(a){u.k.step[a.l]?u.k.step[a.l](a):a.f.style&&(a.f.style[u.ma[a.l]]!=n||u.p[a.l])?u.style(a.f,a.l,a.now+a.sc):a.f[a.l]=a.now}}};D.B.scrollTop=D.B.scrollLeft={set:function(a){a.f.nodeType&&a.f.parentNode&&(a.f[a.l]=a.now)}};
u.a(["toggle","show","hide"],function(a,b){var c=u.b[b];u.b[b]=function(e,f,h){return e==n||"boolean"==typeof e||!a&&u.d(e)&&u.d(f)?c.apply(this,arguments):this.Xa(Ua(b,d),e,f,h)}});
u.b.extend({Ge:function(a,b,c,e){return this.filter(va).g("opacity",0).show().end().Xa({opacity:b},a,c,e)},Xa:function(a,b,c,e){function f(){var b=Ra(this,u.extend({},a),g);h&&b.stop(d)}var h=u.Da(a),g=u.speed(b,c,e);return h||g.j===p?this.a(f):this.j(g.j,f)},stop:function(a,b,c){function e(a){var b=a.stop;delete a.stop;b(c)}return"string"!=typeof a&&(c=b,b=a,a=s),b&&a!==p&&this.j(a||"fx",[]),this.a(function(){var b=d,h=a!=n&&a+"queueHooks",g=u.Oa,j=u.e(this);if(h)j[h]&&j[h].stop&&e(j[h]);else for(h in j)j[h]&&
j[h].stop&&ie.test(h)&&e(j[h]);for(h=g.length;h--;)g[h].f===this&&(a==n||g[h].j===a)&&(g[h].Bc.stop(c),b=p,g.splice(h,1));(b||!c)&&u.$(this,a)})}});u.a({Df:Ua("show"),Ff:Ua("hide"),Ef:Ua("toggle"),Ee:{opacity:"show"},Fe:{opacity:"hide"},He:{opacity:"toggle"}},function(a,b){u.b[a]=function(a,e,f){return this.Xa(b,a,e,f)}});
u.speed=function(a,b,c){var e=a&&"object"==typeof a?u.extend({},a):{complete:c||!c&&b||u.d(a)&&a,duration:a,oa:c&&b||b&&!u.d(b)&&b};e.duration=u.k.G?0:"number"==typeof e.duration?e.duration:e.duration in u.k.Na?u.k.Na[e.duration]:u.k.Na.C;if(e.j==n||e.j===d)e.j="fx";return e.$b=e.complete,e.complete=function(){u.d(e.$b)&&e.$b.call(this);e.j&&u.$(this,e.j)},e};u.oa={Ve:function(a){return a},Jf:function(a){return 0.5-Math.cos(a*Math.PI)/2}};u.Oa=[];u.k=D.prototype.z;
u.k.Td=function(){var a,b=u.Oa,c=0;for(Qa=u.now();c<b.length;c++)a=b[c],!a()&&b[c]===a&&b.splice(c--,1);b.length||u.k.stop();Qa=s};u.k.Ud=function(a){a()&&u.Oa.push(a)&&!fe&&(fe=setInterval(u.k.Td,u.k.cd))};u.k.cd=13;u.k.stop=function(){clearInterval(fe);fe=n};u.k.Na={Gf:600,Ie:200,C:400};u.k.step={};u.q&&u.q.filters&&(u.q.filters.ie=function(a){return u.T(u.Oa,function(b){return a===b.f}).length});var je=/^(?:body|html)$/i;
u.b.offset=function(a){if(arguments.length)return a===s?this:this.a(function(b){u.offset.Od(this,a,b)});var b,c,e,f,h,g,j,k={top:0,left:0},l=this[0],q=l&&l.ownerDocument;if(q)return(c=q.body)===l?u.offset.Hc(l):(b=q.documentElement,u.contains(b,l)?("undefined"!=typeof l.getBoundingClientRect&&(k=l.getBoundingClientRect()),e=Va(q),f=b.clientTop||c.clientTop||0,h=b.clientLeft||c.clientLeft||0,g=e.pageYOffset||b.scrollTop,j=e.pageXOffset||b.scrollLeft,{top:k.top+g-f,left:k.left+j-h}):k)};
u.offset={Hc:function(a){var b=a.offsetTop,c=a.offsetLeft;return u.c.Sc&&(b+=parseFloat(u.g(a,"marginTop"))||0,c+=parseFloat(u.g(a,"marginLeft"))||0),{top:b,left:c}},Od:function(a,b,c){var e=u.g(a,"position");"static"===e&&(a.style.position="relative");var f=u(a),h=f.offset(),g=u.g(a,"top"),j=u.g(a,"left"),k={},l={},q,m;("absolute"===e||"fixed"===e)&&-1<u.L("auto",[g,j])?(l=f.position(),q=l.top,m=l.left):(q=parseFloat(g)||0,m=parseFloat(j)||0);u.d(b)&&(b=b.call(a,c,h));b.top!=n&&(k.top=b.top-h.top+
q);b.left!=n&&(k.left=b.left-h.left+m);"using"in b?b.Uf.call(a,k):f.g(k)}};
u.b.extend({position:function(){if(this[0]){var a=this[0],b=this.offsetParent(),c=this.offset(),e=je.test(b[0].nodeName)?{top:0,left:0}:b.offset();return c.top-=parseFloat(u.g(a,"marginTop"))||0,c.left-=parseFloat(u.g(a,"marginLeft"))||0,e.top+=parseFloat(u.g(b[0],"borderTopWidth"))||0,e.left+=parseFloat(u.g(b[0],"borderLeftWidth"))||0,{top:c.top-e.top,left:c.left-e.left}}},offsetParent:function(){return this.map(function(){for(var a=this.offsetParent||A.body;a&&!je.test(a.nodeName)&&"static"===u.g(a,
"position");)a=a.offsetParent;return a||A.body})}});u.a({scrollLeft:"pageXOffset",scrollTop:"pageYOffset"},function(a,b){var c=/Y/.test(b);u.b[a]=function(e){return u.D(this,function(a,e,g){var j=Va(a);if(g===s)return j?b in j?j[b]:j.document.documentElement[e]:a[e];j?j.scrollTo(c?u(j).scrollLeft():g,c?g:u(j).scrollTop()):a[e]=g},a,e,arguments.length,n)}});
u.a({de:"height",fe:"width"},function(a,b){u.a({padding:"inner"+a,content:b,"":"outer"+a},function(c,e){u.b[e]=function(e,h){var g=arguments.length&&(c||"boolean"!=typeof e),j=c||(e===d||h===d?"margin":"border");return u.D(this,function(b,c,e){var f;return u.U(b)?b.document.documentElement["client"+a]:9===b.nodeType?(f=b.documentElement,Math.max(b.body["scroll"+a],f["scroll"+a],b.body["offset"+a],f["offset"+a],f["client"+a])):e===s?u.g(b,c,e,j):u.style(b,c,e,j)},b,g?e:s,g,n)}})});r.Ha=r.Qa=u;
"function"==typeof define&&define.Ac&&define.Ac.Ha&&define("jquery",[],function(){return u});
